/*
 * LootManager
 * Version 1.0
 *
 * Standalone token-loot handling for the D&D 2024 Beacon sheet.
 * Loot is read from and written to a structured token GM Notes block:
 *
 *   LOOT
 *   gp: 25
 *   item: Potion of Healing
 *   item: Crossbow Bolts | 10
 *   END LOOT
 *
 * Loot contents are never stored in Roll20 state. Only script configuration
 * is persisted there. Items are announced and removed from the source; this
 * script deliberately does not modify Beacon inventory.
 *
 * Commands:
 *   !loot inspect
 *   !loot inspect --token|TOKEN_ID
 *   !loot take ...                         Generated by inspect cards
 *   !loot config
 *   !loot config --delete-when-empty|on
 *   !loot config --item-sound|grab
 *   !loot config --currency-sound|coins
 *   !loot help
 */

const LootManager = (() => {
    'use strict';

    const SCRIPT = 'LootManager';
    const VERSION = '1.0';
    const COMMAND = '!loot';
    const DEFAULT_CONFIG = {
        deleteWhenEmpty: false,
        itemSound: 'grab',
        currencySound: 'coins'
    };
    const GP_READBACK_DELAY = 500;
    const activeTakes = {};
    const activeRecipients = {};

    function checkInstall() {
        state.LootManager = state.LootManager || {};
        state.LootManager.config = state.LootManager.config || {};

        if (typeof state.LootManager.config.deleteWhenEmpty !== 'boolean') {
            state.LootManager.config.deleteWhenEmpty = DEFAULT_CONFIG.deleteWhenEmpty;
        }

        if (typeof state.LootManager.config.itemSound !== 'string') {
            state.LootManager.config.itemSound = DEFAULT_CONFIG.itemSound;
        }

        if (typeof state.LootManager.config.currencySound !== 'string') {
            state.LootManager.config.currencySound = DEFAULT_CONFIG.currencySound;
        }

        state.LootManager.version = VERSION;

        log('=== ' + SCRIPT + ' v' + VERSION + ' Ready ===');
        log('Commands: !loot inspect | !loot config | !loot help');
    }

    function getConfig() {
        return state.LootManager.config;
    }

    function escapeTemplate(value) {
        return String(value === undefined || value === null ? '' : value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/@/g, '&#64;')
            .replace(/=/g, '&#61;')
            .replace(/\{/g, '&#123;')
            .replace(/\}/g, '&#125;')
            .replace(/\|/g, '&#124;');
    }

    function escapeButtonLabel(value) {
        return escapeTemplate(value)
            .replace(/\[/g, '&#91;')
            .replace(/\]/g, '&#93;')
            .replace(/\(/g, '&#40;')
            .replace(/\)/g, '&#41;');
    }

    function encodeOption(value) {
        return encodeURIComponent(String(value === undefined || value === null ? '' : value))
            .replace(/[!'()*]/g, function(character) {
                return '%' + character.charCodeAt(0).toString(16).toUpperCase();
            });
    }

    function decodeOption(value) {
        try {
            return decodeURIComponent(String(value || ''));
        } catch (error) {
            return String(value || '');
        }
    }

    function getPlayerName(msg) {
        const player = getObj('player', msg.playerid);
        const displayName = player
            ? player.get('_displayname')
            : String(msg.who || 'Player').replace(/\s+\(GM\)$/, '');

        return String(displayName || 'Player').replace(/["\\]/g, '');
    }

    function whisper(msg, content) {
        sendChat(SCRIPT, '/w "' + getPlayerName(msg) + '" ' + content);
    }

    function sendCard(msg, title, fields) {
        const body = fields.map(function(field) {
            return '{{' + escapeTemplate(field.label) + '=' + field.value + '}}';
        }).join(' ');

        whisper(
            msg,
            '&{template:default} {{name=' + escapeTemplate(title) + '}} ' + body
        );
    }

    function sendError(msg, message) {
        sendCard(msg, 'Loot Error', [
            {
                label: 'Error',
                value: escapeTemplate(message)
            }
        ]);
    }

    function parseCommand(content) {
        const remainder = String(content || '')
            .replace(/^!loot\b/i, '')
            .trim();
        const parts = remainder ? remainder.split(/\s+--/) : [];
        const actionPart = (parts.shift() || 'inspect').trim();
        const actionTokens = actionPart ? actionPart.split(/\s+/) : [];
        const action = String(actionTokens.shift() || 'inspect').toLowerCase();
        const options = {};

        if (actionTokens.length) {
            options.token = actionTokens.shift();
        }

        parts.forEach(function(part) {
            const separator = part.indexOf('|');
            let key;
            let value;

            if (separator === -1) {
                key = part.trim().toLowerCase();
                value = '';
            } else {
                key = part.slice(0, separator).trim().toLowerCase();
                value = part.slice(separator + 1).trim();
            }

            if (key) options[key] = value;
        });

        return {
            action: action,
            options: options
        };
    }

    function selectedTokenId(msg) {
        const selected = Array.isArray(msg.selected) ? msg.selected : [];
        const tokenSelection = selected.find(function(entry) {
            return entry && entry._type === 'graphic';
        });

        return tokenSelection ? tokenSelection._id : '';
    }

    function resolveToken(msg, tokenId) {
        const requestedId = String(tokenId || selectedTokenId(msg) || '').trim();
        const token = requestedId ? getObj('graphic', requestedId) : null;

        if (!token || token.get('subtype') !== 'token') return null;
        return token;
    }

    function decodePercent(value) {
        const text = String(value || '');

        if (!/%[0-9a-f]{2}/i.test(text)) return text;

        try {
            return decodeURIComponent(text);
        } catch (error) {
            return text;
        }
    }

    function decodeHtmlEntities(value) {
        return String(value || '')
            .replace(/&nbsp;|&#160;/gi, ' ')
            .replace(/&lt;/gi, '<')
            .replace(/&gt;/gi, '>')
            .replace(/&quot;/gi, '"')
            .replace(/&#39;|&apos;/gi, "'")
            .replace(/&#(\d+);/g, function(match, decimal) {
                return String.fromCharCode(parseInt(decimal, 10));
            })
            .replace(/&#x([0-9a-f]+);/gi, function(match, hexadecimal) {
                return String.fromCharCode(parseInt(hexadecimal, 16));
            })
            .replace(/&amp;/gi, '&');
    }

    function gmNotesToText(value) {
        const withoutMarkup = decodePercent(value)
            .replace(/<br\s*\/?>/gi, '\n')
            .replace(/<\/(?:p|div|li|tr|h[1-6])\s*>/gi, '\n')
            .replace(/<li\b[^>]*>/gi, '')
            .replace(/<[^>]*>/g, '')
            .replace(/\r\n?/g, '\n');

        return decodeHtmlEntities(withoutMarkup);
    }

    function findLootBlock(rawNotes) {
        const raw = String(rawNotes || '');
        const startPattern = /(^|%3e|%0a|%0d|[^a-z0-9_])LOOT(?=$|[^a-z0-9_])/gi;
        const endPattern = /END(?:\s|%20|&nbsp;|&#160;|<[^>]+>)+LOOT/gi;
        let startMatch;

        while ((startMatch = startPattern.exec(raw)) !== null) {
            const start = startMatch.index + startMatch[1].length;
            const endSearch = new RegExp(endPattern.source, 'gi');
            let endMatch;

            endSearch.lastIndex = start + 4;

            while ((endMatch = endSearch.exec(raw)) !== null) {
                const end = endMatch.index + endMatch[0].length;
                const candidate = raw.slice(start, end);
                const lines = gmNotesToText(candidate)
                    .split('\n')
                    .map(function(line) {
                        return line.trim();
                    })
                    .filter(function(line) {
                        return line.length > 0;
                    });

                if (
                    lines.length >= 2 &&
                    lines[0].toUpperCase() === 'LOOT' &&
                    lines[lines.length - 1].toUpperCase() === 'END LOOT'
                ) {
                    return {
                        start: start,
                        end: end,
                        raw: candidate,
                        lines: lines
                    };
                }
            }
        }

        return null;
    }

    function parseNonNegativeInteger(value) {
        const text = String(value === undefined || value === null ? '' : value).trim();

        if (!/^\d+$/.test(text)) return null;

        const number = Number(text);
        return isSafeInteger(number) && number >= 0 ? number : null;
    }

    function isSafeInteger(value) {
        return typeof Number.isSafeInteger === 'function'
            ? Number.isSafeInteger(value)
            : isFinite(value) && Math.floor(value) === value && Math.abs(value) <= 9007199254740991;
    }

    function parseLootBlock(block) {
        const entries = [];
        const invalidLines = [];
        let itemIndex = 0;
        let gp = 0;

        block.lines.slice(1, -1).forEach(function(line) {
            const gpMatch = line.match(/^gp\s*:\s*(.+)$/i);
            const itemMatch = line.match(/^item\s*:\s*(.+)$/i);

            if (gpMatch) {
                const amount = parseNonNegativeInteger(gpMatch[1]);
                const combinedGp = amount === null ? null : gp + amount;

                if (amount === null || !isSafeInteger(combinedGp)) {
                    invalidLines.push(line);
                } else {
                    gp = combinedGp;
                }

                return;
            }

            if (itemMatch) {
                const itemParts = itemMatch[1].split('|');
                const name = String(itemParts.shift() || '').trim();
                const quantityText = itemParts.length ? itemParts.join('|').trim() : '1';
                const quantity = parseNonNegativeInteger(quantityText);

                if (!name || quantity === null || itemParts.length > 1) {
                    invalidLines.push(line);
                    return;
                }

                entries.push({
                    index: itemIndex,
                    name: name,
                    quantity: quantity
                });
                itemIndex += 1;
                return;
            }

            invalidLines.push(line);
        });

        return {
            gp: gp,
            items: entries,
            invalidLines: invalidLines
        };
    }

    function getLoot(token) {
        const rawNotes = String(token.get('gmnotes') || '');
        const block = findLootBlock(rawNotes);

        if (!block) {
            return {
                rawNotes: rawNotes,
                block: null,
                gp: 0,
                items: [],
                invalidLines: []
            };
        }

        const parsed = parseLootBlock(block);

        return {
            rawNotes: rawNotes,
            block: block,
            gp: parsed.gp,
            items: parsed.items,
            invalidLines: parsed.invalidLines
        };
    }

    function serializeLoot(loot) {
        const lines = ['LOOT'];

        if (loot.gp > 0) {
            lines.push('gp: ' + loot.gp);
        }

        loot.items.forEach(function(item) {
            if (item.quantity <= 0) return;

            lines.push(
                'item: ' + item.name + (item.quantity === 1 ? '' : ' | ' + item.quantity)
            );
        });

        loot.invalidLines.forEach(function(line) {
            lines.push(line);
        });

        lines.push('END LOOT');
        return lines;
    }

    function escapeGmNotesHtml(value) {
        return String(value || '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
    }

    function formatReplacement(block, lines) {
        if (/%(?:0a|0d|20|3a|3c|3e)/i.test(block.raw)) {
            return encodeURIComponent(lines.join('\n'));
        }

        if (/<[^>]+>/.test(block.raw)) {
            return lines.map(escapeGmNotesHtml).join('<br>');
        }

        return lines.join('\n');
    }

    function writeLoot(token, loot) {
        if (!loot.block) return false;

        const replacement = formatReplacement(loot.block, serializeLoot(loot));
        const updatedNotes = loot.rawNotes.slice(0, loot.block.start) +
            replacement +
            loot.rawNotes.slice(loot.block.end);

        token.set('gmnotes', updatedNotes);
        return true;
    }

    function hasAvailableLoot(loot) {
        return loot.gp > 0 || loot.items.some(function(item) {
            return item.quantity > 0;
        });
    }

    function commandOption(key, value) {
        return ' --' + key + '&#124;' + value;
    }

    function actionButton(label, action) {
        return '[' + escapeButtonLabel(label) + '](' + action + ')';
    }

    function inspectAction(tokenId) {
        return '!loot inspect' + commandOption('token', tokenId);
    }

    function selectedRecipientReference() {
        return '&#64;&#123;selected&#124;token_id&#125;';
    }

    function itemButtons(token, item) {
        const base = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'item') +
            commandOption('index', item.index) +
            commandOption('name', encodeOption(item.name)) +
            commandOption('expected', item.quantity);
        const buttons = [
            actionButton('Take 1', base + commandOption('quantity', 1))
        ];

        if (item.quantity > 1) {
            buttons.push(
                actionButton('Take All', base + commandOption('quantity', item.quantity))
            );
        }

        return buttons.join(' ');
    }

    function currencyButton(token, amount) {
        const action = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'gp') +
            commandOption('amount', amount) +
            commandOption('expected', amount) +
            commandOption('recipient', selectedRecipientReference());

        return actionButton('Take ' + amount + ' gp', action);
    }

    function looseItemButton(token) {
        const action = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'loose') +
            commandOption('name', encodeOption(token.get('name') || 'Loose Item'));

        return actionButton('Take Item', action);
    }

    function showInspectCard(msg, token) {
        const loot = getLoot(token);
        const tokenName = String(token.get('name') || 'Loot');
        const fields = [];

        if (!loot.block) {
            if (token.get('represents')) {
                fields.push({
                    label: 'Loot',
                    value: 'None available.'
                });
            } else {
                fields.push({
                    label: tokenName,
                    value: 'Quantity: 1<br>' + looseItemButton(token)
                });
            }

            sendCard(msg, tokenName + ' Loot', fields);
            return;
        }

        if (loot.gp > 0) {
            fields.push({
                label: 'Currency',
                value: escapeTemplate(loot.gp + ' gp') + '<br>' + currencyButton(token, loot.gp)
            });
        }

        loot.items.forEach(function(item) {
            if (item.quantity <= 0) return;

            fields.push({
                label: item.name,
                value: 'Quantity: ' + escapeTemplate(item.quantity) + '<br>' + itemButtons(token, item)
            });
        });

        if (!hasAvailableLoot(loot)) {
            fields.push({
                label: 'Loot',
                value: 'Empty.'
            });
        }

        if (loot.invalidLines.length) {
            fields.push({
                label: 'Warning',
                value: escapeTemplate(
                    loot.invalidLines.length + ' unrecognized loot ' +
                    (loot.invalidLines.length === 1 ? 'line was' : 'lines were') +
                    ' preserved but cannot be taken.'
                )
            });
        }

        fields.push({
            label: 'Refresh',
            value: actionButton('Inspect Again', inspectAction(token.id))
        });

        sendCard(msg, tokenName + ' Loot', fields);
    }

    function playSound(trackName) {
        const cleanName = String(trackName || '').trim();
        let track;

        if (!cleanName) return true;

        track = findObjs({
            type: 'jukeboxtrack',
            title: cleanName
        })[0];

        if (!track) {
            sendChat(
                SCRIPT,
                '/w gm No Jukebox track was found with the exact name "' +
                escapeTemplate(cleanName) + '".'
            );
            log(SCRIPT + ': No Jukebox track found: ' + cleanName);
            return false;
        }

        track.set('playing', false);
        track.set('softstop', false);
        track.set('playing', true);
        return true;
    }

    function announceTake(msg, sourceName, description) {
        sendChat(
            SCRIPT,
            '&{template:default} {{name=Loot Taken}} ' +
            '{{Who=' + escapeTemplate(getPlayerName(msg)) + '}} ' +
            '{{Source=' + escapeTemplate(sourceName) + '}} ' +
            '{{Taken=' + escapeTemplate(description) + '}}'
        );
    }

    function staleCard(msg, token) {
        sendError(msg, 'That loot card is stale. The source has changed; inspect it again.');

        if (token) showInspectCard(msg, token);
    }

    function parseBeaconGp(value) {
        if (value === undefined || value === null || value === '') return 0;

        const text = String(value).replace(/,/g, '').trim();
        const number = Number(text);

        return isSafeInteger(number) && number >= 0 ? number : null;
    }

    function wait(milliseconds) {
        return new Promise(function(resolve) {
            setTimeout(resolve, milliseconds);
        });
    }

    async function verifyBeaconGp(characterId, expectedGp) {
        let actualGp = parseBeaconGp(await getSheetItem(characterId, 'gp'));

        if (actualGp === expectedGp) return true;

        await wait(GP_READBACK_DELAY);
        actualGp = parseBeaconGp(await getSheetItem(characterId, 'gp'));
        return actualGp === expectedGp;
    }

    async function addGpToRecipient(msg, recipientToken, amount) {
        const characterId = recipientToken ? recipientToken.get('represents') : '';
        let currentGp;
        let updatedGp;

        if (!characterId) {
            sendError(msg, 'Select a token linked to the Beacon character receiving the gp, then use the button again.');
            return false;
        }

        if (
            typeof getSheetItem !== 'function' ||
            typeof setSheetItem !== 'function'
        ) {
            sendError(msg, 'Beacon getSheetItem or setSheetItem is unavailable. No loot was changed.');
            return false;
        }

        try {
            currentGp = parseBeaconGp(await getSheetItem(characterId, 'gp'));

            if (currentGp === null) {
                sendError(msg, 'The selected character has an invalid gp value. No loot was changed.');
                return false;
            }

            updatedGp = currentGp + amount;

            if (!isSafeInteger(updatedGp)) {
                sendError(msg, 'That gp transfer would exceed the supported whole-number range. No loot was changed.');
                return false;
            }

            await setSheetItem(characterId, 'gp', updatedGp);

            if (!await verifyBeaconGp(characterId, updatedGp)) {
                sendError(msg, 'Beacon did not confirm the gp update. The source loot was not changed.');
                return false;
            }

            return true;
        } catch (error) {
            log(SCRIPT + ': Beacon gp update failed: ' + error);
            sendError(msg, 'Beacon gp could not be updated. No loot was changed.');
            return false;
        }
    }

    function finalizeStructuredTake(msg, token, loot, soundName, description) {
        const sourceName = String(token.get('name') || 'Loot Source');
        const deleteWhenEmpty = getConfig().deleteWhenEmpty;
        const empty = !hasAvailableLoot(loot) && loot.invalidLines.length === 0;

        if (empty && deleteWhenEmpty) {
            token.remove();
        } else {
            writeLoot(token, loot);
        }

        playSound(soundName);
        announceTake(msg, sourceName, description);

        if (!empty || !deleteWhenEmpty) {
            showInspectCard(msg, token);
        }
    }

    async function takeGp(msg, token, options) {
        const loot = getLoot(token);
        const expected = parseNonNegativeInteger(options.expected);
        const amount = parseNonNegativeInteger(options.amount);
        const recipientToken = resolveToken(msg, options.recipient);
        let recipientCharacterId;

        if (
            !loot.block ||
            expected === null ||
            amount === null ||
            amount <= 0 ||
            loot.gp !== expected ||
            amount > loot.gp
        ) {
            staleCard(msg, token);
            return;
        }

        if (!recipientToken) {
            sendError(msg, 'Select a valid linked recipient token, then use the currency button again.');
            return;
        }

        recipientCharacterId = String(recipientToken.get('represents') || '');

        if (!recipientCharacterId) {
            sendError(msg, 'Select a token linked to the Beacon character receiving the gp, then use the button again.');
            return;
        }

        if (activeRecipients[recipientCharacterId]) {
            sendError(msg, 'Another gp transfer to that character is still processing. Inspect the source again before retrying.');
            return;
        }

        activeRecipients[recipientCharacterId] = true;

        try {
            if (!await addGpToRecipient(msg, recipientToken, amount)) return;

            loot.gp -= amount;
            finalizeStructuredTake(
                msg,
                token,
                loot,
                getConfig().currencySound,
                amount + ' gp'
            );
        } finally {
            delete activeRecipients[recipientCharacterId];
        }
    }

    function takeItem(msg, token, options) {
        const loot = getLoot(token);
        const index = parseNonNegativeInteger(options.index);
        const expected = parseNonNegativeInteger(options.expected);
        const quantity = parseNonNegativeInteger(options.quantity);
        const expectedName = decodeOption(options.name);
        const item = index === null ? null : loot.items.find(function(entry) {
            return entry.index === index;
        });

        if (
            !loot.block ||
            !item ||
            expected === null ||
            quantity === null ||
            quantity <= 0 ||
            item.name !== expectedName ||
            item.quantity !== expected ||
            quantity > item.quantity
        ) {
            staleCard(msg, token);
            return;
        }

        item.quantity -= quantity;
        finalizeStructuredTake(
            msg,
            token,
            loot,
            getConfig().itemSound,
            item.name + (quantity === 1 ? '' : ' x' + quantity)
        );
    }

    function takeLooseItem(msg, token, options) {
        const loot = getLoot(token);
        const expectedName = decodeOption(options.name);
        const currentName = String(token.get('name') || 'Loose Item');

        if (token.get('represents') || loot.block || currentName !== expectedName) {
            staleCard(msg, token);
            return;
        }

        token.remove();
        playSound(getConfig().itemSound);
        announceTake(msg, currentName, currentName);
    }

    async function handleTake(msg, options) {
        const token = resolveToken(msg, options.token);
        const type = String(options.type || '').toLowerCase();

        if (!token) {
            sendError(msg, 'The loot source no longer exists.');
            return;
        }

        if (activeTakes[token.id]) {
            sendError(msg, 'Another take from this source is still processing. Inspect it again before retrying.');
            return;
        }

        activeTakes[token.id] = true;

        try {
            switch (type) {
                case 'gp':
                    await takeGp(msg, token, options);
                    break;

                case 'item':
                    takeItem(msg, token, options);
                    break;

                case 'loose':
                    takeLooseItem(msg, token, options);
                    break;

                default:
                    sendError(msg, 'Unknown loot type. Inspect the source to create a fresh button.');
                    break;
            }
        } finally {
            delete activeTakes[token.id];
        }
    }

    function parseToggle(value) {
        const normalized = String(value || '').trim().toLowerCase();

        if (/^(?:on|yes|true|1)$/.test(normalized)) return true;
        if (/^(?:off|no|false|0)$/.test(normalized)) return false;
        return null;
    }

    function showConfig(msg) {
        const config = getConfig();

        sendCard(msg, 'LootManager Configuration', [
            {
                label: 'Delete When Empty',
                value: config.deleteWhenEmpty ? 'On' : 'Off'
            },
            {
                label: 'Item Sound',
                value: escapeTemplate(config.itemSound || 'Disabled')
            },
            {
                label: 'Currency Sound',
                value: escapeTemplate(config.currencySound || 'Disabled')
            },
            {
                label: 'Commands',
                value: '!loot config --delete-when-empty&#124;on<br>' +
                    '!loot config --item-sound&#124;grab<br>' +
                    '!loot config --currency-sound&#124;coins<br>' +
                    'Use clear as either sound name to disable it.'
            }
        ]);
    }

    function handleConfig(msg, options) {
        const config = getConfig();
        let toggle;

        if (!playerIsGM(msg.playerid)) {
            sendError(msg, 'Only the GM can change LootManager configuration.');
            return;
        }

        if (options['delete-when-empty'] !== undefined) {
            toggle = parseToggle(options['delete-when-empty']);

            if (toggle === null) {
                sendError(msg, 'Delete-when-empty must be on or off.');
                return;
            }

            config.deleteWhenEmpty = toggle;
        }

        if (options['item-sound'] !== undefined) {
            config.itemSound = String(options['item-sound']).trim();
            if (config.itemSound.toLowerCase() === 'clear') config.itemSound = '';
        }

        if (options['currency-sound'] !== undefined) {
            config.currencySound = String(options['currency-sound']).trim();
            if (config.currencySound.toLowerCase() === 'clear') config.currencySound = '';
        }

        showConfig(msg);
    }

    function showHelp(msg) {
        sendCard(msg, 'LootManager Commands', [
            {
                label: 'Inspect Selected',
                value: '!loot inspect'
            },
            {
                label: 'Inspect Target Macro',
                value: '!loot inspect --token&#124;&#64;&#123;target&#124;Loot Source&#124;token_id&#125;'
            },
            {
                label: 'Take Items',
                value: 'Use the buttons on the inspect card. Items are removed from the source but are not added to Beacon inventory.'
            },
            {
                label: 'Take Currency',
                value: 'Select the linked recipient token before using the gp button. Currency is added to that character\'s Beacon gp field.'
            },
            {
                label: 'Loot Block',
                value: 'LOOT<br>gp: 25<br>item: Potion of Healing<br>item: Crossbow Bolts &#124; 10<br>END LOOT'
            },
            {
                label: 'GM Configuration',
                value: '!loot config'
            }
        ]);
    }

    async function handleInput(msg) {
        const command = parseCommand(msg.content);
        let token;

        if (msg.type !== 'api' || !/^!loot(?:\s|$)/i.test(msg.content)) return;

        switch (command.action) {
            case 'inspect':
            case 'show':
                token = resolveToken(msg, command.options.token);

                if (!token) {
                    sendError(msg, 'Select a token or specify one with --token|TOKEN_ID.');
                    return;
                }

                showInspectCard(msg, token);
                break;

            case 'take':
                await handleTake(msg, command.options);
                break;

            case 'config':
                handleConfig(msg, command.options);
                break;

            case 'help':
                showHelp(msg);
                break;

            default:
                sendError(msg, 'Unknown command. Use !loot help for the command list.');
                break;
        }
    }

    function registerEventHandlers() {
        on('chat:message', function(msg) {
            handleInput(msg).catch(function(error) {
                log(SCRIPT + ': Unexpected error: ' + error);
                sendError(msg, 'An unexpected error occurred. No further loot changes were attempted.');
            });
        });
    }

    on('ready', function() {
        checkInstall();
        registerEventHandlers();
    });

    return {
        inspect: function(tokenId) {
            const token = getObj('graphic', tokenId);
            return token && token.get('subtype') === 'token' ? getLoot(token) : null;
        }
    };
})();
