/*
 * LootManager
 * Version 1.3.1
 *
 * Standalone token-loot handling for the D&D 2024 Beacon sheet.
 * Loot is read from and written to a structured token GM Notes block:
 *
 *   LOOT
 *   gp: 25
 *   item: Potion of Healing
 *   item: Crossbow Bolts | 10
 *   handout: Expedition Diary
 *   key-item: Iron Gate Key
 *   END LOOT
 *
 * Loot contents are never stored in Roll20 state. Only script configuration
 * is persisted there. Items are announced and removed from the source; this
 * script deliberately does not modify Beacon inventory.
 *
 * Commands:
 *   !loot LOOTER_TOKEN_ID TARGET_TOKEN_ID   Universal player command
 *   !loot inspect
 *   !loot inspect --token|TOKEN_ID
 *   !loot unlock-check LOOTER_TOKEN_ID CONTAINER_TOKEN_ID
 *   !loot use-key LOOTER_TOKEN_ID CONTAINER_TOKEN_ID
 *   !loot take ...                         Generated by inspect cards
 *   !loot config
 *   !loot keys
 *   !loot config --delete-when-empty|on
 *   !loot config --item-sound|grab
 *   !loot config --currency-sound|coins
 *   !loot help
 */

const LootManager = (() => {
    'use strict';

    const SCRIPT = 'LootManager';
    const VERSION = '1.3.1';
    const COMMAND = '!loot';
    const KEYS_PAGE_SIZE = 8;
    const DEFAULT_CONFIG = {
        deleteWhenEmpty: false,
        itemSound: 'grab',
        currencySound: 'coins'
    };
    const GP_READBACK_DELAY = 500;
    const activeTakes = {};
    const activeRecipients = {};
    const activeReveals = {};
    const activeUnlocks = {};

    function checkInstall() {
        state.LootManager = state.LootManager || {};
        state.LootManager.config = state.LootManager.config || {};
        if (
            !state.LootManager.keys ||
            typeof state.LootManager.keys !== 'object' ||
            Array.isArray(state.LootManager.keys)
        ) {
            state.LootManager.keys = {};
        }

        if (typeof state.LootManager.config.deleteWhenEmpty !== 'boolean') {
            state.LootManager.config.deleteWhenEmpty = DEFAULT_CONFIG.deleteWhenEmpty;
        }

        if (typeof state.LootManager.config.itemSound !== 'string') {
            state.LootManager.config.itemSound = DEFAULT_CONFIG.itemSound;
        }

        if (typeof state.LootManager.config.currencySound !== 'string') {
            state.LootManager.config.currencySound = DEFAULT_CONFIG.currencySound;
        }

        state.LootManager.version = VERSION;

        log('=== ' + SCRIPT + ' v' + VERSION + ' Ready ===');
        log('Commands: !loot LOOTER TARGET | !loot inspect | !loot config | !loot keys | !loot help');
    }

    function getConfig() {
        return state.LootManager.config;
    }

    function normalizeKeyName(name) {
        return String(name || '')
            .trim()
            .replace(/\s+/g, ' ')
            .toLowerCase();
    }

    function cleanKeyName(name) {
        return String(name || '')
            .trim()
            .replace(/\s+/g, ' ');
    }

    function getKeyState() {
        state.LootManager = state.LootManager || {};

        if (
            !state.LootManager.keys ||
            typeof state.LootManager.keys !== 'object' ||
            Array.isArray(state.LootManager.keys)
        ) {
            state.LootManager.keys = {};
        }

        return state.LootManager.keys;
    }

    function isKeyring(value) {
        return !!value && typeof value === 'object' && !Array.isArray(value);
    }

    function getKeyring(characterId, create) {
        const characterKey = String(characterId || '');
        const keys = getKeyState();

        if (!characterKey) return null;

        if (!isKeyring(keys[characterKey])) {
            if (!create) return null;
            keys[characterKey] = {};
        }

        return keys[characterKey];
    }

    function getKeyringEntries(characterId) {
        const keyring = getKeyring(characterId, false);

        if (!keyring) return [];

        return Object.keys(keyring).map(function(normalizedName) {
            const record = keyring[normalizedName];
            const name = record && typeof record.name === 'string'
                ? cleanKeyName(record.name)
                : '';

            if (
                !normalizedName ||
                normalizeKeyName(normalizedName) !== normalizedName ||
                !name ||
                normalizeKeyName(name) !== normalizedName
            ) {
                return null;
            }

            return {
                normalizedName: normalizedName,
                name: name
            };
        }).filter(function(entry) {
            return !!entry;
        }).sort(function(left, right) {
            return left.name.toLowerCase().localeCompare(right.name.toLowerCase());
        });
    }

    function characterHasKey(characterId, keyName) {
        const normalizedName = normalizeKeyName(keyName);
        const keyring = getKeyring(characterId, false);
        const record = keyring && keyring[normalizedName];

        return !!(
            normalizedName &&
            record &&
            typeof record.name === 'string' &&
            normalizeKeyName(record.name) === normalizedName
        );
    }

    function grantCharacterKey(characterId, keyName) {
        const name = cleanKeyName(keyName);
        const normalizedName = normalizeKeyName(name);
        const keyring = getKeyring(characterId, true);

        if (!name || !normalizedName || !keyring) {
            return {
                ok: false,
                added: false,
                name: ''
            };
        }

        if (characterHasKey(characterId, normalizedName)) {
            return {
                ok: true,
                added: false,
                name: keyring[normalizedName].name
            };
        }

        keyring[normalizedName] = {
            name: name
        };

        return {
            ok: true,
            added: true,
            name: name
        };
    }

    function removeCharacterKey(characterId, keyName) {
        const normalizedName = normalizeKeyName(keyName);
        const keyring = getKeyring(characterId, false);

        if (!normalizedName || !keyring || !characterHasKey(characterId, normalizedName)) {
            return false;
        }

        delete keyring[normalizedName];

        if (!Object.keys(keyring).length) {
            delete getKeyState()[String(characterId || '')];
        }

        return true;
    }

    function countKeyRecords(keyring) {
        return isKeyring(keyring) ? Object.keys(keyring).length : 0;
    }

    function escapeTemplate(value) {
        return String(value === undefined || value === null ? '' : value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/@/g, '&#64;')
            .replace(/=/g, '&#61;')
            .replace(/\{/g, '&#123;')
            .replace(/\}/g, '&#125;')
            .replace(/\|/g, '&#124;');
    }

    function escapeButtonLabel(value) {
        return escapeTemplate(value)
            .replace(/\[/g, '&#91;')
            .replace(/\]/g, '&#93;')
            .replace(/\(/g, '&#40;')
            .replace(/\)/g, '&#41;');
    }

    function encodeOption(value) {
        return encodeURIComponent(String(value === undefined || value === null ? '' : value))
            .replace(/[!'()*]/g, function(character) {
                return '%' + character.charCodeAt(0).toString(16).toUpperCase();
            });
    }

    function decodeOption(value) {
        try {
            return decodeURIComponent(String(value || ''));
        } catch (error) {
            return String(value || '');
        }
    }

    function getPlayerName(msg) {
        const player = getObj('player', msg.playerid);
        const displayName = player
            ? player.get('_displayname')
            : String(msg.who || 'Player').replace(/\s+\(GM\)$/, '');

        return String(displayName || 'Player').replace(/["\\]/g, '');
    }

    function whisper(msg, content) {
        sendChat(SCRIPT, '/w "' + getPlayerName(msg) + '" ' + content);
    }

    function sendCard(msg, title, fields) {
        const body = fields.map(function(field) {
            return '{{' + escapeTemplate(field.label) + '=' + field.value + '}}';
        }).join(' ');

        whisper(
            msg,
            '&{template:default} {{name=' + escapeTemplate(title) + '}} ' + body
        );
    }

    function sendError(msg, message) {
        sendCard(msg, 'Loot Error', [
            {
                label: 'Error',
                value: escapeTemplate(message)
            }
        ]);
    }

    function parseCommand(content) {
        const remainder = String(content || '')
            .replace(/^!loot\b/i, '')
            .trim();
        const parts = remainder ? remainder.split(/\s+--/) : [];
        const actionPart = (parts.shift() || 'inspect').trim();
        const actionTokens = actionPart ? actionPart.split(/\s+/) : [];
        const actionRaw = String(actionTokens.shift() || 'inspect');
        const action = actionRaw.toLowerCase();
        const positionals = actionTokens.slice();
        const options = {};

        if (actionTokens.length) {
            options.token = actionTokens.shift();
        }

        parts.forEach(function(part) {
            const separator = part.indexOf('|');
            let key;
            let value;

            if (separator === -1) {
                key = part.trim().toLowerCase();
                value = '';
            } else {
                key = part.slice(0, separator).trim().toLowerCase();
                value = part.slice(separator + 1).trim();
            }

            if (key) options[key] = value;
        });

        return {
            action: action,
            actionRaw: actionRaw,
            positionals: positionals,
            options: options
        };
    }

    function selectedTokenId(msg) {
        const selected = Array.isArray(msg.selected) ? msg.selected : [];
        const tokenSelection = selected.find(function(entry) {
            return entry && entry._type === 'graphic';
        });

        return tokenSelection ? tokenSelection._id : '';
    }

    function resolveToken(msg, tokenId) {
        const requestedId = String(tokenId || selectedTokenId(msg) || '').trim();
        const token = requestedId ? getObj('graphic', requestedId) : null;

        if (!token || token.get('subtype') !== 'token') return null;
        return token;
    }

    function decodePercent(value) {
        const text = String(value || '');

        if (!/%[0-9a-f]{2}/i.test(text)) return text;

        try {
            return decodeURIComponent(text);
        } catch (error) {
            return text;
        }
    }

    function decodeHtmlEntities(value) {
        return String(value || '')
            .replace(/&nbsp;|&#160;/gi, ' ')
            .replace(/&lt;/gi, '<')
            .replace(/&gt;/gi, '>')
            .replace(/&quot;/gi, '"')
            .replace(/&#39;|&apos;/gi, "'")
            .replace(/&#(\d+);/g, function(match, decimal) {
                return String.fromCharCode(parseInt(decimal, 10));
            })
            .replace(/&#x([0-9a-f]+);/gi, function(match, hexadecimal) {
                return String.fromCharCode(parseInt(hexadecimal, 16));
            })
            .replace(/&amp;/gi, '&');
    }

    function gmNotesToText(value) {
        const withoutMarkup = decodePercent(value)
            .replace(/<br\s*\/?>/gi, '\n')
            .replace(/<\/(?:p|div|li|tr|h[1-6])\s*>/gi, '\n')
            .replace(/<li\b[^>]*>/gi, '')
            .replace(/<[^>]*>/g, '')
            .replace(/\r\n?/g, '\n');

        return decodeHtmlEntities(withoutMarkup);
    }

    function findLootBlock(rawNotes) {
        const raw = String(rawNotes || '');
        const startPattern = /(^|%3e|%0a|%0d|[^a-z0-9_])LOOT(?=$|[^a-z0-9_])/gi;
        const endPattern = /END(?:\s|%20|&nbsp;|&#160;|<[^>]+>)+LOOT/gi;
        let startMatch;

        while ((startMatch = startPattern.exec(raw)) !== null) {
            const start = startMatch.index + startMatch[1].length;
            const endSearch = new RegExp(endPattern.source, 'gi');
            let endMatch;

            endSearch.lastIndex = start + 4;

            while ((endMatch = endSearch.exec(raw)) !== null) {
                const end = endMatch.index + endMatch[0].length;
                const candidate = raw.slice(start, end);
                const lines = gmNotesToText(candidate)
                    .split('\n')
                    .map(function(line) {
                        return line.trim();
                    })
                    .filter(function(line) {
                        return line.length > 0;
                    });

                if (
                    lines.length >= 2 &&
                    lines[0].toUpperCase() === 'LOOT' &&
                    lines[lines.length - 1].toUpperCase() === 'END LOOT'
                ) {
                    return {
                        start: start,
                        end: end,
                        raw: candidate,
                        lines: lines
                    };
                }
            }
        }

        return null;
    }

    function parseNonNegativeInteger(value) {
        const text = String(value === undefined || value === null ? '' : value).trim();

        if (!/^\d+$/.test(text)) return null;

        const number = Number(text);
        return isSafeInteger(number) && number >= 0 ? number : null;
    }

    function isSafeInteger(value) {
        return typeof Number.isSafeInteger === 'function'
            ? Number.isSafeInteger(value)
            : isFinite(value) && Math.floor(value) === value && Math.abs(value) <= 9007199254740991;
    }

    function parseLootBlock(block) {
        const entries = [];
        const handouts = [];
        const keyItems = [];
        const invalidLines = [];
        const records = [];
        const unresolvedGp = [];
        const container = {
            type: '',
            locked: false,
            lockedSpecified: false,
            lockDc: '',
            closedSide: '',
            openSide: '',
            lockedRecord: null,
            keyName: '',
            keyNormalized: '',
            keyRecord: null
        };
        let itemIndex = 0;
        let handoutIndex = 0;
        let keyIndex = 0;
        let gp = 0;

        block.lines.slice(1, -1).forEach(function(line, sourceIndex) {
            const canonicalInlineMatch = line.match(/^gp\s*:\s*\[\[([\s\S]+)\]\]\s*$/i);
            const alternateInlineMatch = line.match(/^\[\[([\s\S]+)\]\]\s*gp\s*$/i);
            const gpMatch = line.match(/^gp\s*:\s*(.+)$/i);
            const itemMatch = line.match(/^item\s*:\s*(.+)$/i);
            const handoutMatch = line.match(/^handout\s*:\s*(.*)$/i);
            const keyItemMatch = line.match(/^key-item\s*:\s*(.*)$/i);
            const fieldMatch = line.match(/^(type|locked|key|lock-dc|closed-side|open-side)\s*:\s*(.*?)\s*$/i);
            let record;

            if (canonicalInlineMatch || alternateInlineMatch) {
                record = {
                    kind: 'gp-inline',
                    raw: line,
                    sourceIndex: sourceIndex,
                    expression: String(
                        canonicalInlineMatch ? canonicalInlineMatch[1] : alternateInlineMatch[1]
                    ).trim()
                };

                if (!record.expression) {
                    record.kind = 'invalid';
                    invalidLines.push(line);
                } else {
                    unresolvedGp.push(record);
                }

                records.push(record);
                return;
            }

            if (gpMatch) {
                const amount = parseNonNegativeInteger(gpMatch[1]);
                const combinedGp = amount === null ? null : gp + amount;

                record = {
                    kind: amount === null || !isSafeInteger(combinedGp) ? 'invalid' : 'gp',
                    raw: line,
                    sourceIndex: sourceIndex,
                    amount: amount
                };

                if (amount === null || !isSafeInteger(combinedGp)) {
                    invalidLines.push(line);
                } else {
                    gp = combinedGp;
                }

                records.push(record);
                return;
            }

            if (itemMatch) {
                const itemParts = itemMatch[1].split('|');
                const name = String(itemParts.shift() || '').trim();
                const quantityText = itemParts.length ? itemParts.join('|').trim() : '1';
                const quantity = parseNonNegativeInteger(quantityText);

                if (!name || quantity === null || itemParts.length > 1) {
                    invalidLines.push(line);
                    records.push({
                        kind: 'invalid',
                        raw: line,
                        sourceIndex: sourceIndex
                    });
                    return;
                }

                record = {
                    kind: 'item',
                    raw: line,
                    sourceIndex: sourceIndex,
                    index: itemIndex,
                    name: name,
                    quantity: quantity
                };
                entries.push(record);
                records.push(record);
                itemIndex += 1;
                return;
            }

            if (handoutMatch) {
                const name = String(handoutMatch[1] || '').trim();

                if (!name) {
                    invalidLines.push(line);
                    records.push({
                        kind: 'invalid',
                        raw: line,
                        sourceIndex: sourceIndex
                    });
                    return;
                }

                record = {
                    kind: 'handout',
                    raw: line,
                    sourceIndex: sourceIndex,
                    index: handoutIndex,
                    name: name
                };
                handouts.push(record);
                records.push(record);
                handoutIndex += 1;
                return;
            }

            if (keyItemMatch) {
                const name = cleanKeyName(keyItemMatch[1]);
                const normalizedName = normalizeKeyName(name);

                if (!name || !normalizedName) {
                    invalidLines.push(line);
                    records.push({
                        kind: 'invalid',
                        raw: line,
                        sourceIndex: sourceIndex
                    });
                    return;
                }

                record = {
                    kind: 'key',
                    raw: line,
                    sourceIndex: sourceIndex,
                    index: keyIndex,
                    name: name,
                    normalizedName: normalizedName
                };
                keyItems.push(record);
                records.push(record);
                keyIndex += 1;
                return;
            }

            if (fieldMatch) {
                const key = fieldMatch[1].toLowerCase();
                const value = String(fieldMatch[2] || '').trim();

                record = {
                    kind: 'field',
                    raw: line,
                    sourceIndex: sourceIndex,
                    key: key,
                    value: value
                };
                records.push(record);

                switch (key) {
                    case 'type':
                        container.type = value.toLowerCase();
                        break;

                    case 'locked':
                        container.lockedSpecified = true;
                        container.locked = value.toLowerCase() === 'yes';
                        container.lockedRecord = record;
                        break;

                    case 'key':
                        container.keyName = cleanKeyName(value);
                        container.keyNormalized = normalizeKeyName(container.keyName);
                        container.keyRecord = record;
                        break;

                    case 'lock-dc':
                        container.lockDc = value;
                        break;

                    case 'closed-side':
                        container.closedSide = value;
                        break;

                    case 'open-side':
                        container.openSide = value;
                        break;
                }

                return;
            }

            invalidLines.push(line);
            records.push({
                kind: 'invalid',
                raw: line,
                sourceIndex: sourceIndex
            });
        });

        records.forEach(function(record, recordIndex) {
            if (record.kind !== 'handout' && record.kind !== 'key') return;

            record.previousRaw = recordIndex > 0
                ? records[recordIndex - 1].raw
                : 'LOOT';
            record.nextRaw = recordIndex < records.length - 1
                ? records[recordIndex + 1].raw
                : 'END LOOT';
        });

        return {
            gp: gp,
            items: entries,
            handouts: handouts,
            keyItems: keyItems,
            invalidLines: invalidLines,
            records: records,
            unresolvedGp: unresolvedGp,
            container: container
        };
    }

    function getLoot(token) {
        const rawNotes = String(token.get('gmnotes') || '');
        const block = findLootBlock(rawNotes);

        if (!block) {
            return {
                rawNotes: rawNotes,
                block: null,
                gp: 0,
                items: [],
                handouts: [],
                keyItems: [],
                invalidLines: [],
                records: [],
                unresolvedGp: [],
                container: {
                    type: '',
                    locked: false,
                    lockedSpecified: false,
                    lockDc: '',
                    closedSide: '',
                    openSide: '',
                    lockedRecord: null,
                    keyName: '',
                    keyNormalized: '',
                    keyRecord: null
                }
            };
        }

        const parsed = parseLootBlock(block);

        return {
            rawNotes: rawNotes,
            block: block,
            gp: parsed.gp,
            items: parsed.items,
            handouts: parsed.handouts,
            keyItems: parsed.keyItems,
            invalidLines: parsed.invalidLines,
            records: parsed.records,
            unresolvedGp: parsed.unresolvedGp,
            container: parsed.container
        };
    }

    function serializeLoot(loot) {
        const lines = ['LOOT'];

        loot.records.forEach(function(record) {
            if (record.removed) return;
            if (record.kind === 'item' && record.quantity <= 0) return;

            lines.push(record.replacement === undefined ? record.raw : record.replacement);
        });

        lines.push('END LOOT');
        return lines;
    }

    function setFixedGpTotal(loot, amount) {
        const gpRecords = loot.records.filter(function(record) {
            return record.kind === 'gp';
        });

        gpRecords.forEach(function(record) {
            record.removed = true;
        });

        if (amount > 0 && gpRecords.length) {
            gpRecords[0].removed = false;
            gpRecords[0].amount = amount;
            gpRecords[0].replacement = 'gp: ' + amount;
        }

        loot.gp = amount;
    }

    function setItemQuantity(item, quantity) {
        item.quantity = quantity;

        if (quantity <= 0) {
            item.removed = true;
            return;
        }

        item.replacement = 'item: ' + item.name + (quantity === 1 ? '' : ' | ' + quantity);
    }

    function setContainerLocked(loot, locked) {
        const record = loot.container && loot.container.lockedRecord;

        if (!record) return false;

        record.value = locked ? 'yes' : 'no';
        record.replacement = record.raw.replace(
            /^(locked\s*:\s*).*$/i,
            '$1' + record.value
        );
        loot.container.locked = locked;
        return true;
    }

    function escapeGmNotesHtml(value) {
        return String(value || '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
    }

    function formatReplacement(block, lines) {
        if (/%(?:0a|0d|20|3a|3c|3e)/i.test(block.raw)) {
            return encodeURIComponent(lines.join('\n'));
        }

        if (/<[^>]+>/.test(block.raw)) {
            return lines.map(escapeGmNotesHtml).join('<br>');
        }

        return lines.join('\n');
    }

    function writeLoot(token, loot) {
        if (!loot.block) return false;

        const replacement = formatReplacement(loot.block, serializeLoot(loot));
        const updatedNotes = loot.rawNotes.slice(0, loot.block.start) +
            replacement +
            loot.rawNotes.slice(loot.block.end);

        token.set('gmnotes', updatedNotes);
        return true;
    }

    function hasAvailableLoot(loot) {
        return loot.gp > 0 || loot.unresolvedGp.length > 0 ||
            loot.items.some(function(item) {
                return item.quantity > 0;
            }) || loot.handouts.some(function(handout) {
                return !handout.removed;
            }) || loot.keyItems.some(function(keyItem) {
                return !keyItem.removed;
            });
    }

    function commandOption(key, value) {
        return ' --' + key + '&#124;' + value;
    }

    function actionButton(label, action) {
        return '[' + escapeButtonLabel(label) + '](' + action + ')';
    }

    function inspectAction(tokenId, looterTokenId) {
        if (looterTokenId) {
            return '!loot ' + looterTokenId + ' ' + tokenId;
        }

        return '!loot inspect' + commandOption('token', tokenId);
    }

    function selectedRecipientReference() {
        return '&#64;&#123;selected&#124;token_id&#125;';
    }

    function itemButtons(token, item) {
        const base = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'item') +
            commandOption('index', item.index) +
            commandOption('name', encodeOption(item.name)) +
            commandOption('expected', item.quantity);
        const buttons = [
            actionButton('Take 1', base + commandOption('quantity', 1))
        ];

        if (item.quantity > 1) {
            buttons.push(
                actionButton('Take All', base + commandOption('quantity', item.quantity))
            );
        }

        return buttons.join(' ');
    }

    function currencyButton(token, amount, recipientToken) {
        const action = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'gp') +
            commandOption('amount', amount) +
            commandOption('expected', amount) +
            commandOption(
                'recipient',
                recipientToken ? recipientToken.id : selectedRecipientReference()
            );

        return actionButton('Take ' + amount + ' gp', action);
    }

    function handoutButton(token, handout, looterToken) {
        const action = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'handout') +
            commandOption('index', handout.index) +
            commandOption('source-index', handout.sourceIndex) +
            commandOption('name', encodeOption(handout.name)) +
            commandOption('before', encodeOption(handout.previousRaw)) +
            commandOption('after', encodeOption(handout.nextRaw)) +
            (looterToken ? commandOption('looter', looterToken.id) : '');

        return actionButton('Take and Read', action);
    }

    function keyItemButton(token, keyItem, looterToken) {
        const action = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'key') +
            commandOption('index', keyItem.index) +
            commandOption('source-index', keyItem.sourceIndex) +
            commandOption('name', encodeOption(keyItem.name)) +
            commandOption('before', encodeOption(keyItem.previousRaw)) +
            commandOption('after', encodeOption(keyItem.nextRaw)) +
            commandOption(
                'looter',
                looterToken ? looterToken.id : selectedRecipientReference()
            );

        return actionButton('Take Key', action);
    }

    function looseItemButton(token) {
        const action = '!loot take' +
            commandOption('token', token.id) +
            commandOption('type', 'loose') +
            commandOption('name', encodeOption(token.get('name') || 'Loose Item'));

        return actionButton('Take Item', action);
    }

    function showInspectCard(msg, token, looterToken) {
        const loot = getLoot(token);
        const tokenName = String(token.get('name') || 'Loot');
        const fields = [];

        if (!loot.block) {
            if (token.get('represents')) {
                fields.push({
                    label: 'Loot',
                    value: 'None available.'
                });
            } else {
                fields.push({
                    label: tokenName,
                    value: 'Quantity: 1<br>' + looseItemButton(token)
                });
            }

            sendCard(msg, tokenName + ' Loot', fields);
            return;
        }

        if (loot.gp > 0) {
            fields.push({
                label: 'Currency',
                value: escapeTemplate(loot.gp + ' Gold Pieces') + '<br>' +
                    currencyButton(token, loot.gp, looterToken)
            });
        }

        loot.items.forEach(function(item) {
            if (item.quantity <= 0) return;

            fields.push({
                label: item.name,
                value: 'Quantity: ' + escapeTemplate(item.quantity) + '<br>' + itemButtons(token, item)
            });
        });

        loot.handouts.forEach(function(handout) {
            fields.push({
                label: handout.name,
                value: 'Handout<br>' + handoutButton(token, handout, looterToken)
            });
        });

        loot.keyItems.forEach(function(keyItem) {
            fields.push({
                label: keyItem.name,
                value: 'Key<br>' + keyItemButton(token, keyItem, looterToken)
            });
        });

        if (!hasAvailableLoot(loot)) {
            fields.push({
                label: 'Loot',
                value: 'Empty.'
            });
        }

        if (loot.invalidLines.length) {
            fields.push({
                label: 'Warning',
                value: escapeTemplate(
                    loot.invalidLines.length + ' unrecognized loot ' +
                    (loot.invalidLines.length === 1 ? 'line was' : 'lines were') +
                    ' preserved but cannot be taken.'
                )
            });
        }

        fields.push({
            label: 'Refresh',
            value: actionButton(
                'Inspect Again',
                inspectAction(token.id, looterToken ? looterToken.id : '')
            )
        });

        sendCard(msg, tokenName + ' Loot', fields);
    }

    function isContainer(loot) {
        return !!(
            loot &&
            loot.block &&
            loot.container &&
            loot.container.type === 'container'
        );
    }

    function sendGmWarning(message) {
        sendChat(
            SCRIPT,
            '/w gm &{template:default} {{name=LootManager Warning}} ' +
            '{{Warning=' + escapeTemplate(message) + '}}'
        );
    }

    function getCleanTokenImgsrc(imgsrc) {
        const rawSource = String(imgsrc || '');
        let cleanSource = rawSource;
        let match;

        try {
            cleanSource = decodeURIComponent(rawSource);
        } catch (error) {
            cleanSource = rawSource;
        }

        match = cleanSource.match(/(.*\/images\/.*)(thumb|med|original|max)([^?]*)(\?[^?]+)?$/);
        if (!match) return null;

        return match[1] + 'thumb' + match[3] + (match[4] || '');
    }

    function setContainerSide(token, sideValue, label) {
        const configuredSide = parseNonNegativeInteger(sideValue);
        const rawSides = String(token && token.get('sides') || '');
        const sides = rawSides ? rawSides.split('|').filter(function(side) {
            return side !== '';
        }) : [];
        let imgsrc;

        if (!token) return false;

        if (sides.length < 2) {
            sendGmWarning(
                String(token.get('name') || 'Container') +
                ' is not a multi-sided token; its ' + label + ' side could not be set.'
            );
            return false;
        }

        if (configuredSide === null || configuredSide < 1) {
            sendGmWarning(
                String(token.get('name') || 'Container') +
                ' has no valid positive-integer ' + label + '-side setting.'
            );
            return false;
        }

        if (configuredSide > sides.length) {
            sendGmWarning(
                String(token.get('name') || 'Container') + ' has ' + sides.length +
                ' sides, so configured ' + label + '-side ' + configuredSide + ' is out of range.'
            );
            return false;
        }

        imgsrc = getCleanTokenImgsrc(sides[configuredSide - 1]);

        if (!imgsrc) {
            sendGmWarning(
                String(token.get('name') || 'Container') +
                ' has an unusable image URL for configured ' + label + '-side ' + configuredSide + '.'
            );
            return false;
        }

        try {
            token.set({
                currentSide: configuredSide - 1,
                imgsrc: imgsrc
            });
        } catch (error) {
            log(SCRIPT + ': Container side update failed: ' + error);
            sendGmWarning(
                String(token.get('name') || 'Container') +
                ' could not change to configured ' + label + '-side ' + configuredSide + '.'
            );
            return false;
        }

        return true;
    }

    function unlockButton(looterToken, containerToken) {
        if (!looterToken || !containerToken) return '';

        return actionButton(
            'Perform Sleight of Hand Check',
            '!loot unlock-check ' + looterToken.id + ' ' + containerToken.id
        );
    }

    function useKeyButton(looterToken, containerToken, keyName) {
        if (!looterToken || !containerToken || !keyName) return '';

        return actionButton(
            'Use Key',
            '!loot use-key ' + looterToken.id + ' ' + containerToken.id +
            commandOption('key', encodeOption(keyName))
        );
    }

    function showLockedContainerCard(msg, looterToken, containerToken, loot) {
        const fields = [
            {
                label: 'Status',
                value: 'This container is locked.'
            }
        ];
        const button = unlockButton(looterToken, containerToken);
        const characterId = String(looterToken && looterToken.get('represents') || '');
        const keyButton = loot && loot.container && loot.container.keyNormalized &&
            getObj('character', characterId) &&
            characterHasKey(characterId, loot.container.keyNormalized)
            ? useKeyButton(looterToken, containerToken, loot.container.keyNormalized)
            : '';

        if (button) {
            fields.push({
                label: 'Action',
                value: button + (keyButton ? '<br>' + keyButton : '')
            });
        } else {
            fields.push({
                label: 'Action',
                value: 'Use the universal Loot macro with a selected looter token to attempt the lock.'
            });
        }

        sendCard(
            msg,
            String(containerToken.get('name') || 'Container'),
            fields
        );
    }

    function parseFiniteNumber(value) {
        const text = String(value === undefined || value === null ? '' : value).trim();
        const number = Number(text);

        return text && isFinite(number) ? number : null;
    }

    function evaluateRollExpression(expression) {
        return new Promise(function(resolve, reject) {
            const cleanExpression = String(expression || '').trim();

            if (!cleanExpression) {
                reject(new Error('The roll expression is empty.'));
                return;
            }

            sendChat(
                SCRIPT,
                '/w gm [[' + cleanExpression + ']]',
                function(messages) {
                    const message = messages && messages[0];
                    const roll = message && message.inlinerolls && message.inlinerolls[0];
                    const total = roll && roll.results
                        ? Number(roll.results.total)
                        : NaN;

                    if (!isFinite(total)) {
                        reject(new Error('Roll20 did not return a finite inline-roll total.'));
                        return;
                    }

                    resolve(total);
                },
                {
                    noarchive: true,
                    use3d: false
                }
            );
        });
    }

    async function resolveInlineGold(msg, token) {
        if (activeReveals[token.id]) {
            sendError(msg, 'This loot source is already being revealed. Try again after it finishes.');
            return false;
        }

        activeReveals[token.id] = true;

        try {
            const loot = getLoot(token);
            const resolvedRecords = [];
            let combinedGp = loot.gp;
            let persistedLoot;

            if (!loot.unresolvedGp.length) return true;

            for (let index = 0; index < loot.unresolvedGp.length; index += 1) {
                const record = loot.unresolvedGp[index];
                let total;

                try {
                    total = await evaluateRollExpression(record.expression);
                } catch (error) {
                    log(SCRIPT + ': Inline gold roll failed: ' + error);
                    sendGmWarning(
                        'Could not resolve inline gold for ' +
                        String(token.get('name') || 'loot source') + ': ' + error
                    );
                    sendError(msg, 'The gold roll could not be resolved. The loot was not revealed or changed.');
                    return false;
                }

                if (!isSafeInteger(total) || total < 0) {
                    sendGmWarning(
                        'Inline gold for ' + String(token.get('name') || 'loot source') +
                        ' resolved to unsupported value ' + total + '.'
                    );
                    sendError(msg, 'The gold roll did not produce a supported whole-number amount. The loot was not revealed or changed.');
                    return false;
                }

                combinedGp += total;

                if (!isSafeInteger(combinedGp)) {
                    sendGmWarning(
                        'Resolved gold for ' + String(token.get('name') || 'loot source') +
                        ' would exceed the supported whole-number range.'
                    );
                    sendError(msg, 'The resolved gold total is too large to store safely. The loot was not revealed or changed.');
                    return false;
                }

                resolvedRecords.push({
                    record: record,
                    total: total
                });
            }

            resolvedRecords.forEach(function(resolved) {
                const record = resolved.record;

                record.kind = 'gp';
                record.amount = resolved.total;
                record.expression = '';
                record.replacement = 'gp: ' + resolved.total;
            });

            try {
                if (!writeLoot(token, loot)) {
                    throw new Error('The LOOT block could not be written.');
                }
            } catch (error) {
                log(SCRIPT + ': Resolved gold GM Notes write failed: ' + error);
                sendGmWarning(
                    'Rolled gold for ' + String(token.get('name') || 'loot source') +
                    ' but could not write the resolved amount: ' + error
                );
                sendError(msg, 'The gold was rolled but could not be saved, so the loot card was not displayed.');
                return false;
            }

            persistedLoot = getLoot(token);

            if (!resolvedRecords.every(function(resolved) {
                const persisted = persistedLoot.records.find(function(currentRecord) {
                    return currentRecord.sourceIndex === resolved.record.sourceIndex;
                });

                return persisted &&
                    persisted.kind === 'gp' &&
                    persisted.amount === resolved.total;
            })) {
                sendGmWarning(
                    'The resolved gold write for ' +
                    String(token.get('name') || 'loot source') +
                    ' could not be verified. The loot card was withheld.'
                );
                sendError(msg, 'The resolved gold could not be verified in GM Notes, so the loot was not displayed.');
                return false;
            }

            return true;
        } finally {
            delete activeReveals[token.id];
        }
    }

    async function inspectLoot(msg, looterToken, targetToken, options) {
        const settings = options || {};
        let loot = getLoot(targetToken);

        if (!loot.block) {
            showInspectCard(msg, targetToken, looterToken);
            return true;
        }

        if (isContainer(loot) && loot.container.locked) {
            setContainerSide(targetToken, loot.container.closedSide, 'closed');
            showLockedContainerCard(msg, looterToken, targetToken, loot);
            return true;
        }

        if (isContainer(loot) && !settings.skipContainerSide) {
            setContainerSide(targetToken, loot.container.openSide, 'open');
        }

        if (loot.unresolvedGp.length) {
            if (!await resolveInlineGold(msg, targetToken)) return false;
            loot = getLoot(targetToken);

            if (loot.unresolvedGp.length) {
                sendError(msg, 'Unresolved gold remains in this loot source, so the loot card was not displayed.');
                return false;
            }
        }

        showInspectCard(msg, targetToken, looterToken);
        return true;
    }

    function playSound(trackName) {
        const cleanName = String(trackName || '').trim();
        let track;

        if (!cleanName) return true;

        track = findObjs({
            type: 'jukeboxtrack',
            title: cleanName
        })[0];

        if (!track) {
            sendChat(
                SCRIPT,
                '/w gm No Jukebox track was found with the exact name "' +
                escapeTemplate(cleanName) + '".'
            );
            log(SCRIPT + ': No Jukebox track found: ' + cleanName);
            return false;
        }

        track.set('playing', false);
        track.set('softstop', false);
        track.set('playing', true);
        return true;
    }

    function announceTake(msg, sourceName, description) {
        sendChat(
            SCRIPT,
            '&{template:default} {{name=Loot Taken}} ' +
            '{{Who=' + escapeTemplate(getPlayerName(msg)) + '}} ' +
            '{{Source=' + escapeTemplate(sourceName) + '}} ' +
            '{{Taken=' + escapeTemplate(description) + '}}'
        );
    }

    async function staleCard(msg, token, looterToken) {
        sendError(msg, 'That loot card is stale. The source has changed; inspect it again.');

        if (token) await inspectLoot(msg, looterToken || null, token);
    }

    function parseBeaconGp(value) {
        if (value === undefined || value === null || value === '') return 0;

        const text = String(value).replace(/,/g, '').trim();
        const number = Number(text);

        return isSafeInteger(number) && number >= 0 ? number : null;
    }

    function wait(milliseconds) {
        return new Promise(function(resolve) {
            setTimeout(resolve, milliseconds);
        });
    }

    async function verifyBeaconGp(characterId, expectedGp) {
        let actualGp = parseBeaconGp(await getSheetItem(characterId, 'gp'));

        if (actualGp === expectedGp) return true;

        await wait(GP_READBACK_DELAY);
        actualGp = parseBeaconGp(await getSheetItem(characterId, 'gp'));
        return actualGp === expectedGp;
    }

    async function addGpToRecipient(msg, recipientToken, amount) {
        const characterId = recipientToken ? recipientToken.get('represents') : '';
        let currentGp;
        let updatedGp;

        if (!characterId) {
            sendError(msg, 'Select a token linked to the Beacon character receiving the gp, then use the button again.');
            return {
                ok: false,
                newTotal: null
            };
        }

        if (
            typeof getSheetItem !== 'function' ||
            typeof setSheetItem !== 'function'
        ) {
            sendError(msg, 'Beacon getSheetItem or setSheetItem is unavailable. No loot was changed.');
            return {
                ok: false,
                newTotal: null
            };
        }

        try {
            currentGp = parseBeaconGp(await getSheetItem(characterId, 'gp'));

            if (currentGp === null) {
                sendError(msg, 'The selected character has an invalid gp value. No loot was changed.');
                return {
                    ok: false,
                    newTotal: null
                };
            }

            updatedGp = currentGp + amount;

            if (!isSafeInteger(updatedGp)) {
                sendError(msg, 'That gp transfer would exceed the supported whole-number range. No loot was changed.');
                return {
                    ok: false,
                    newTotal: null
                };
            }

            await setSheetItem(characterId, 'gp', updatedGp);

            if (!await verifyBeaconGp(characterId, updatedGp)) {
                sendError(msg, 'Beacon did not confirm the gp update. The source loot was not changed.');
                return {
                    ok: false,
                    newTotal: null
                };
            }

            return {
                ok: true,
                newTotal: updatedGp
            };
        } catch (error) {
            log(SCRIPT + ': Beacon gp update failed: ' + error);
            sendError(msg, 'Beacon gp could not be updated. No loot was changed.');
            return {
                ok: false,
                newTotal: null
            };
        }
    }

    async function finalizeStructuredTake(msg, token, loot, soundName, description, options) {
        const sourceName = String(token.get('name') || 'Loot Source');
        const deleteWhenEmpty = getConfig().deleteWhenEmpty;
        const empty = !hasAvailableLoot(loot) && loot.invalidLines.length === 0;
        const settings = options || {};
        const shouldWrite = !empty || !deleteWhenEmpty || settings.writeBeforeDelete;

        if (shouldWrite) {
            if (settings.verifyWrite) {
                try {
                    if (!writeLoot(token, loot)) {
                        throw new Error('Loot GM Notes could not be updated.');
                    }

                    if (!settings.verifyWrite(getLoot(token))) {
                        throw new Error('Loot GM Notes update could not be verified.');
                    }
                } catch (error) {
                    log(SCRIPT + ': ' + error);
                    sendGmWarning(settings.gmWriteError ||
                        'Loot was changed, but its GM Notes update could not be verified.');
                    sendError(msg, settings.playerWriteError ||
                        'The loot was changed, but the source could not be updated.');
                    return false;
                }
            } else {
                writeLoot(token, loot);
            }
        }

        if (empty && deleteWhenEmpty) {
            token.remove();
        }

        playSound(soundName);
        announceTake(msg, sourceName, description);

        if (!empty || !deleteWhenEmpty) {
            await inspectLoot(msg, null, token);
        }

        return true;
    }

    async function takeGp(msg, token, options) {
        const loot = getLoot(token);
        const expected = parseNonNegativeInteger(options.expected);
        const amount = parseNonNegativeInteger(options.amount);
        const recipientToken = resolveToken(msg, options.recipient);
        let recipientCharacterId;
        let transfer;

        if (
            !loot.block ||
            (isContainer(loot) && loot.container.locked) ||
            loot.unresolvedGp.length > 0 ||
            expected === null ||
            amount === null ||
            amount <= 0 ||
            loot.gp !== expected ||
            amount > loot.gp
        ) {
            await staleCard(msg, token);
            return;
        }

        if (!recipientToken) {
            sendError(msg, 'Select a valid linked recipient token, then use the currency button again.');
            return;
        }

        recipientCharacterId = String(recipientToken.get('represents') || '');

        if (!recipientCharacterId) {
            sendError(msg, 'Select a token linked to the Beacon character receiving the gp, then use the button again.');
            return;
        }

        if (activeRecipients[recipientCharacterId]) {
            sendError(msg, 'Another gp transfer to that character is still processing. Inspect the source again before retrying.');
            return;
        }

        activeRecipients[recipientCharacterId] = true;

        try {
            transfer = await addGpToRecipient(msg, recipientToken, amount);
            if (!transfer.ok) return;

            setFixedGpTotal(loot, loot.gp - amount);
            await finalizeStructuredTake(
                msg,
                token,
                loot,
                getConfig().currencySound,
                amount + ' gp; new character total: ' + transfer.newTotal + ' gp'
            );
        } finally {
            delete activeRecipients[recipientCharacterId];
        }
    }

    async function takeItem(msg, token, options) {
        const loot = getLoot(token);
        const index = parseNonNegativeInteger(options.index);
        const expected = parseNonNegativeInteger(options.expected);
        const quantity = parseNonNegativeInteger(options.quantity);
        const expectedName = decodeOption(options.name);
        const item = index === null ? null : loot.items.find(function(entry) {
            return entry.index === index;
        });

        if (
            !loot.block ||
            (isContainer(loot) && loot.container.locked) ||
            loot.unresolvedGp.length > 0 ||
            !item ||
            expected === null ||
            quantity === null ||
            quantity <= 0 ||
            item.name !== expectedName ||
            item.quantity !== expected ||
            quantity > item.quantity
        ) {
            await staleCard(msg, token);
            return;
        }

        setItemQuantity(item, item.quantity - quantity);
        await finalizeStructuredTake(
            msg,
            token,
            loot,
            getConfig().itemSound,
            item.name + (quantity === 1 ? '' : ' x' + quantity)
        );
    }

    async function takeHandout(msg, token, options) {
        const loot = getLoot(token);
        const index = parseNonNegativeInteger(options.index);
        const sourceIndex = parseNonNegativeInteger(options['source-index']);
        const expectedName = decodeOption(options.name);
        const expectedBefore = decodeOption(options.before);
        const expectedAfter = decodeOption(options.after);
        const handout = index === null ? null : loot.handouts.find(function(entry) {
            return entry.index === index;
        });
        const recordIndex = handout ? loot.records.indexOf(handout) : -1;
        const currentBefore = recordIndex > 0
            ? loot.records[recordIndex - 1].raw
            : 'LOOT';
        const currentAfter = recordIndex >= 0 && recordIndex < loot.records.length - 1
            ? loot.records[recordIndex + 1].raw
            : 'END LOOT';
        let result;
        let matchingEntries;

        if (
            !loot.block ||
            (isContainer(loot) && loot.container.locked) ||
            loot.unresolvedGp.length > 0 ||
            !handout ||
            sourceIndex === null ||
            handout.sourceIndex !== sourceIndex ||
            handout.name !== expectedName ||
            currentBefore !== expectedBefore ||
            currentAfter !== expectedAfter
        ) {
            await staleCard(msg, token);
            return;
        }

        if (
            typeof HandoutAccess === 'undefined' ||
            !HandoutAccess ||
            typeof HandoutAccess.revealByReference !== 'function'
        ) {
            sendGmWarning(
                'HandoutAccess.revealByReference is unavailable. Handout "' +
                handout.name + '" remains in ' +
                String(token.get('name') || 'the loot source') + '.'
            );
            sendError(msg, 'Handout access is unavailable. The handout remains in the loot.');
            return;
        }

        try {
            result = HandoutAccess.revealByReference(
                handout.name,
                msg.playerid,
                {
                    announce: true
                }
            );
        } catch (error) {
            log(SCRIPT + ': HandoutAccess reveal failed: ' + error);
            sendGmWarning(
                'Handout "' + handout.name + '" could not be granted: ' + error
            );
            sendError(msg, 'The handout could not be granted. The handout remains in the loot.');
            return;
        }

        if (!result || result.ok !== true) {
            sendGmWarning(
                'Handout "' + handout.name + '" could not be granted: ' +
                String(result && result.error || 'HandoutAccess did not return success.')
            );
            sendError(msg, 'The handout could not be granted. The handout remains in the loot.');
            return;
        }

        matchingEntries = loot.handouts.filter(function(entry) {
            return entry.name === handout.name;
        }).length;
        handout.removed = true;

        await finalizeStructuredTake(
            msg,
            token,
            loot,
            getConfig().itemSound,
            handout.name + ' handout',
            {
                writeBeforeDelete: true,
                verifyWrite: function(persisted) {
                    return persisted.handouts.filter(function(entry) {
                        return entry.name === handout.name;
                    }).length === matchingEntries - 1;
                },
                playerWriteError: 'Handout access was granted, but the loot entry could not be removed.',
                gmWriteError: 'Handout "' + handout.name + '" was granted to ' +
                    getPlayerName(msg) + ', but the loot entry could not be removed. ' +
                    'The player still has access to the handout.'
            }
        );
    }

    async function takeKey(msg, token, options) {
        const loot = getLoot(token);
        const index = parseNonNegativeInteger(options.index);
        const sourceIndex = parseNonNegativeInteger(options['source-index']);
        const expectedName = decodeOption(options.name);
        const expectedBefore = decodeOption(options.before);
        const expectedAfter = decodeOption(options.after);
        const keyItem = index === null ? null : loot.keyItems.find(function(entry) {
            return entry.index === index;
        });
        const recordIndex = keyItem ? loot.records.indexOf(keyItem) : -1;
        const currentBefore = recordIndex > 0
            ? loot.records[recordIndex - 1].raw
            : 'LOOT';
        const currentAfter = recordIndex >= 0 && recordIndex < loot.records.length - 1
            ? loot.records[recordIndex + 1].raw
            : 'END LOOT';
        const looterToken = resolveToken(msg, options.looter);
        const characterId = String(looterToken && looterToken.get('represents') || '');
        const character = characterId ? getObj('character', characterId) : null;
        let matchingEntries;
        let keyResult;

        if (
            !loot.block ||
            (isContainer(loot) && loot.container.locked) ||
            loot.unresolvedGp.length > 0 ||
            !keyItem ||
            sourceIndex === null ||
            keyItem.sourceIndex !== sourceIndex ||
            keyItem.name !== expectedName ||
            currentBefore !== expectedBefore ||
            currentAfter !== expectedAfter
        ) {
            await staleCard(msg, token);
            return;
        }

        if (!looterToken) {
            sendError(msg, 'Select a valid linked looter token, then use the key button again.');
            return;
        }

        if (!characterId) {
            sendError(msg, 'The looter token must represent a character to take a key.');
            return;
        }

        if (!character) {
            sendError(msg, 'The looter token represents a character that no longer exists.');
            return;
        }

        keyResult = grantCharacterKey(characterId, keyItem.name);

        if (!keyResult.ok) {
            sendError(msg, 'The key name is invalid. The loot was not changed.');
            return;
        }

        matchingEntries = loot.keyItems.filter(function(entry) {
            return entry.name === keyItem.name;
        }).length;
        keyItem.removed = true;

        await finalizeStructuredTake(
            msg,
            token,
            loot,
            getConfig().itemSound,
            keyResult.name,
            {
                writeBeforeDelete: true,
                verifyWrite: function(persisted) {
                    return persisted.keyItems.filter(function(entry) {
                        return entry.name === keyItem.name;
                    }).length === matchingEntries - 1;
                },
                playerWriteError: 'The key was added, but the loot entry could not be removed.',
                gmWriteError: 'Key "' + keyResult.name + '" was added to ' +
                    String(character.get('name') || characterId) +
                    ', but the loot entry could not be removed.'
            }
        );
    }

    async function takeLooseItem(msg, token, options) {
        const loot = getLoot(token);
        const expectedName = decodeOption(options.name);
        const currentName = String(token.get('name') || 'Loose Item');

        if (token.get('represents') || loot.block || currentName !== expectedName) {
            await staleCard(msg, token);
            return;
        }

        token.remove();
        playSound(getConfig().itemSound);
        announceTake(msg, currentName, currentName);
    }

    async function handleTake(msg, options) {
        const token = resolveToken(msg, options.token);
        const type = String(options.type || '').toLowerCase();

        if (!token) {
            sendError(msg, 'The loot source no longer exists.');
            return;
        }

        if (activeTakes[token.id]) {
            sendError(msg, 'Another take from this source is still processing. Inspect it again before retrying.');
            return;
        }

        activeTakes[token.id] = true;

        try {
            switch (type) {
                case 'gp':
                    await takeGp(msg, token, options);
                    break;

                case 'item':
                    await takeItem(msg, token, options);
                    break;

                case 'handout':
                    await takeHandout(msg, token, options);
                    break;

                case 'key':
                    await takeKey(msg, token, options);
                    break;

                case 'loose':
                    await takeLooseItem(msg, token, options);
                    break;

                default:
                    sendError(msg, 'Unknown loot type. Inspect the source to create a fresh button.');
                    break;
            }
        } finally {
            delete activeTakes[token.id];
        }
    }

    function getLooterDisplayName(looterToken) {
        const characterId = looterToken ? looterToken.get('represents') : '';
        const character = characterId ? getObj('character', characterId) : null;

        return String(
            character && character.get('name') ||
            looterToken && looterToken.get('name') ||
            'Looter'
        );
    }

    function formatSignedNumber(value) {
        return value >= 0 ? '+' + value : String(value);
    }

    function showUnlockResultCard(
        msg,
        looterToken,
        containerToken,
        naturalRoll,
        bonus,
        total,
        lockDc,
        success
    ) {
        const fields = [
            {
                label: 'Character',
                value: escapeTemplate(getLooterDisplayName(looterToken))
            },
            {
                label: 'Natural d20',
                value: escapeTemplate(naturalRoll)
            },
            {
                label: 'Sleight of Hand Bonus',
                value: escapeTemplate(formatSignedNumber(bonus))
            },
            {
                label: 'Total',
                value: escapeTemplate(total)
            },
            {
                label: 'Lock DC',
                value: escapeTemplate(lockDc)
            },
            {
                label: 'Result',
                value: success ? 'Success' : 'Failure'
            }
        ];

        if (!success) {
            fields.push({
                label: 'Retry',
                value: unlockButton(looterToken, containerToken)
            });
        }

        sendCard(
            msg,
            String(containerToken.get('name') || 'Container') + ' Lock Check',
            fields
        );
    }

    async function handleUnlockCheck(msg, looterTokenId, containerTokenId) {
        const looterToken = resolveToken(msg, looterTokenId);
        const containerToken = resolveToken(msg, containerTokenId);
        let loot;
        let characterId;
        let lockDc;
        let bonus;
        let naturalRoll;
        let total;
        let success;
        let persisted;

        if (!looterToken || !containerToken) {
            sendError(msg, 'The looter token or container token no longer exists.');
            return;
        }

        loot = getLoot(containerToken);

        if (!loot.block) {
            sendError(msg, 'The target no longer has a valid LOOT block.');
            return;
        }

        if (!isContainer(loot)) {
            sendError(msg, 'The target is no longer marked as a container.');
            return;
        }

        if (!loot.container.locked) {
            await inspectLoot(msg, looterToken, containerToken);
            return;
        }

        characterId = String(looterToken.get('represents') || '');

        if (!characterId) {
            sendError(msg, 'The looter token must represent a Beacon character.');
            return;
        }

        lockDc = parseFiniteNumber(loot.container.lockDc);

        if (lockDc === null) {
            sendGmWarning(
                String(containerToken.get('name') || 'Container') +
                ' has a missing or invalid lock-dc value.'
            );
            sendError(msg, 'This container does not have a valid lock DC.');
            return;
        }

        if (typeof getSheetItem !== 'function') {
            sendError(msg, 'Beacon getSheetItem is unavailable, so the lock check cannot be made.');
            return;
        }

        if (activeUnlocks[containerToken.id]) {
            sendError(msg, 'A lock check for this container is already processing.');
            return;
        }

        activeUnlocks[containerToken.id] = true;

        try {
            loot = getLoot(containerToken);

            if (!loot.block || !isContainer(loot)) {
                sendError(msg, 'The container configuration changed before the check could begin.');
                return;
            }

            if (!loot.container.locked) {
                await inspectLoot(msg, looterToken, containerToken);
                return;
            }

            lockDc = parseFiniteNumber(loot.container.lockDc);

            if (lockDc === null) {
                sendGmWarning(
                    String(containerToken.get('name') || 'Container') +
                    ' has a missing or invalid current lock-dc value.'
                );
                sendError(msg, 'This container no longer has a valid lock DC.');
                return;
            }

            setContainerSide(containerToken, loot.container.closedSide, 'closed');

            try {
                bonus = parseFiniteNumber(
                    await getSheetItem(characterId, 'sleight_of_hand_bonus')
                );
            } catch (error) {
                log(SCRIPT + ': Sleight of Hand bonus read failed: ' + error);
                sendError(msg, 'The character\'s Sleight of Hand bonus could not be read.');
                return;
            }

            if (bonus === null) {
                sendError(msg, 'The character has an invalid Sleight of Hand bonus.');
                return;
            }

            try {
                naturalRoll = await evaluateRollExpression('1d20');
            } catch (error) {
                log(SCRIPT + ': Sleight of Hand d20 roll failed: ' + error);
                sendError(msg, 'Roll20 could not complete the Sleight of Hand check.');
                return;
            }

            total = naturalRoll + bonus;

            if (!isFinite(naturalRoll) || !isFinite(total)) {
                sendError(msg, 'The Sleight of Hand check returned an invalid result.');
                return;
            }

            success = total >= lockDc;

            if (!success) {
                showUnlockResultCard(
                    msg,
                    looterToken,
                    containerToken,
                    naturalRoll,
                    bonus,
                    total,
                    lockDc,
                    false
                );
                return;
            }

            if (!setContainerLocked(loot, false)) {
                sendError(msg, 'The container lock setting could not be updated.');
                return;
            }

            try {
                if (!writeLoot(containerToken, loot)) {
                    throw new Error('The LOOT block could not be written.');
                }
            } catch (error) {
                log(SCRIPT + ': Container unlock GM Notes write failed: ' + error);
                sendGmWarning(
                    'The lock check succeeded for ' +
                    String(containerToken.get('name') || 'container') +
                    ', but locked: no could not be written: ' + error
                );
                sendError(msg, 'The check succeeded, but the unlocked state could not be saved.');
                return;
            }

            persisted = getLoot(containerToken);

            if (!isContainer(persisted) || persisted.container.locked) {
                sendGmWarning(
                    'The unlocked state for ' +
                    String(containerToken.get('name') || 'container') +
                    ' could not be verified in GM Notes.'
                );
                sendError(msg, 'The check succeeded, but the unlocked state could not be verified.');
                return;
            }

            showUnlockResultCard(
                msg,
                looterToken,
                containerToken,
                naturalRoll,
                bonus,
                total,
                lockDc,
                true
            );
            if (!setContainerSide(containerToken, persisted.container.openSide, 'open')) {
                sendError(msg, 'The lock was opened, but the container image could not be changed.');
            }
            playSound(getConfig().itemSound);
            await inspectLoot(
                msg,
                looterToken,
                containerToken,
                {
                    skipContainerSide: true
                }
            );
        } finally {
            delete activeUnlocks[containerToken.id];
        }
    }

    async function handleUseKey(msg, looterTokenId, containerTokenId, options) {
        const looterToken = resolveToken(msg, looterTokenId);
        const containerToken = resolveToken(msg, containerTokenId);
        const expectedKey = normalizeKeyName(decodeOption(options.key));
        let loot;
        let characterId;
        let character;
        let persisted;

        if (!looterToken || !containerToken) {
            sendError(msg, 'The looter token or container token no longer exists.');
            return;
        }

        loot = getLoot(containerToken);

        if (!loot.block) {
            sendError(msg, 'The target no longer has a valid LOOT block.');
            return;
        }

        if (!isContainer(loot)) {
            sendError(msg, 'The target is no longer marked as a container.');
            return;
        }

        if (!loot.container.locked) {
            await inspectLoot(msg, looterToken, containerToken);
            return;
        }

        characterId = String(looterToken.get('represents') || '');
        character = characterId ? getObj('character', characterId) : null;

        if (!characterId || !character) {
            sendError(msg, 'The looter token must represent a current character to use a key.');
            return;
        }

        if (
            !expectedKey ||
            !loot.container.keyNormalized ||
            loot.container.keyNormalized !== expectedKey ||
            !characterHasKey(characterId, expectedKey)
        ) {
            await staleCard(msg, containerToken, looterToken);
            return;
        }

        if (activeUnlocks[containerToken.id]) {
            sendError(msg, 'A container unlock is already processing.');
            return;
        }

        activeUnlocks[containerToken.id] = true;

        try {
            loot = getLoot(containerToken);

            if (!loot.block || !isContainer(loot)) {
                sendError(msg, 'The container configuration changed before the key could be used.');
                return;
            }

            if (!loot.container.locked) {
                await inspectLoot(msg, looterToken, containerToken);
                return;
            }

            if (
                !loot.container.keyNormalized ||
                loot.container.keyNormalized !== expectedKey ||
                !characterHasKey(characterId, expectedKey)
            ) {
                await staleCard(msg, containerToken, looterToken);
                return;
            }

            if (!setContainerLocked(loot, false)) {
                sendError(msg, 'The container lock setting could not be updated.');
                return;
            }

            try {
                if (!writeLoot(containerToken, loot)) {
                    throw new Error('The LOOT block could not be written.');
                }
            } catch (error) {
                log(SCRIPT + ': Key unlock GM Notes write failed: ' + error);
                sendGmWarning(
                    'Key unlock for ' +
                    String(containerToken.get('name') || 'container') +
                    ' could not write locked: no: ' + error
                );
                sendError(msg, 'The key fits, but the unlocked state could not be saved.');
                return;
            }

            persisted = getLoot(containerToken);

            if (
                !isContainer(persisted) ||
                persisted.container.locked ||
                persisted.container.keyNormalized !== expectedKey
            ) {
                sendGmWarning(
                    'The key unlock state for ' +
                    String(containerToken.get('name') || 'container') +
                    ' could not be verified in GM Notes.'
                );
                sendError(msg, 'The key fit, but the unlocked state could not be verified.');
                return;
            }

            setContainerSide(containerToken, persisted.container.openSide, 'open');
            playSound(getConfig().itemSound);
            await inspectLoot(
                msg,
                looterToken,
                containerToken,
                {
                    skipContainerSide: true
                }
            );
        } finally {
            delete activeUnlocks[containerToken.id];
        }
    }

    function parseToggle(value) {
        const normalized = String(value || '').trim().toLowerCase();

        if (/^(?:on|yes|true|1)$/.test(normalized)) return true;
        if (/^(?:off|no|false|0)$/.test(normalized)) return false;
        return null;
    }

    function showConfig(msg) {
        const config = getConfig();

        sendCard(msg, 'LootManager Configuration', [
            {
                label: 'Delete When Empty',
                value: config.deleteWhenEmpty ? 'On' : 'Off'
            },
            {
                label: 'Item Sound',
                value: escapeTemplate(config.itemSound || 'Disabled')
            },
            {
                label: 'Currency Sound',
                value: escapeTemplate(config.currencySound || 'Disabled')
            },
            {
                label: 'Commands',
                value: '!loot config --delete-when-empty&#124;on<br>' +
                    '!loot config --item-sound&#124;grab<br>' +
                    '!loot config --currency-sound&#124;coins<br>' +
                    'Use clear as either sound name to disable it.'
            }
        ]);
    }

    function handleConfig(msg, options) {
        const config = getConfig();
        let toggle;

        if (!playerIsGM(msg.playerid)) {
            sendError(msg, 'Only the GM can change LootManager configuration.');
            return;
        }

        if (options['delete-when-empty'] !== undefined) {
            toggle = parseToggle(options['delete-when-empty']);

            if (toggle === null) {
                sendError(msg, 'Delete-when-empty must be on or off.');
                return;
            }

            config.deleteWhenEmpty = toggle;
        }

        if (options['item-sound'] !== undefined) {
            config.itemSound = String(options['item-sound']).trim();
            if (config.itemSound.toLowerCase() === 'clear') config.itemSound = '';
        }

        if (options['currency-sound'] !== undefined) {
            config.currencySound = String(options['currency-sound']).trim();
            if (config.currencySound.toLowerCase() === 'clear') config.currencySound = '';
        }

        showConfig(msg);
    }

    function getKeyringSummaries() {
        const keys = getKeyState();

        return Object.keys(keys).map(function(characterId) {
            const character = getObj('character', characterId);

            return {
                characterId: characterId,
                character: character,
                name: character
                    ? String(character.get('name') || 'Unnamed Character')
                    : 'Missing Character',
                keyCount: countKeyRecords(keys[characterId])
            };
        }).sort(function(left, right) {
            if (!!left.character !== !!right.character) {
                return left.character ? -1 : 1;
            }

            const nameComparison = left.name.toLowerCase().localeCompare(right.name.toLowerCase());

            return nameComparison || left.characterId.localeCompare(right.characterId);
        });
    }

    function keyConfirmationQuery(prompt) {
        return '?&#123;' + prompt + '&#124;no&#125;';
    }

    function showKeysMenu(msg, requestedPage, notice) {
        const summaries = getKeyringSummaries();
        const totalKeyRecords = summaries.reduce(function(total, summary) {
            return total + summary.keyCount;
        }, 0);
        const pageCount = Math.max(1, Math.ceil(summaries.length / KEYS_PAGE_SIZE));
        const parsedPage = parseNonNegativeInteger(requestedPage);
        const page = Math.min(
            pageCount,
            Math.max(1, parsedPage === null || parsedPage === 0 ? 1 : parsedPage)
        );
        const start = (page - 1) * KEYS_PAGE_SIZE;
        const fields = [];
        const pageButtons = [];

        if (notice) {
            fields.push({
                label: 'Result',
                value: escapeTemplate(notice)
            });
        }

        fields.push({
            label: 'Keyrings',
            value: escapeTemplate(summaries.length + ' character keyring' +
                (summaries.length === 1 ? '' : 's'))
        });
        fields.push({
            label: 'Stored Keys',
            value: escapeTemplate(totalKeyRecords)
        });

        if (!summaries.length) {
            fields.push({
                label: 'Keyrings',
                value: 'No character keyrings are stored.'
            });
        } else {
            summaries.slice(start, start + KEYS_PAGE_SIZE).forEach(function(summary) {
                fields.push({
                    label: summary.name,
                    value: 'Character ID: ' + escapeTemplate(summary.characterId) + '<br>' +
                        'Stored keys: ' + escapeTemplate(summary.keyCount) + '<br>' +
                        actionButton(
                            'Open Keyring',
                            '!loot keys' + commandOption(
                                'character',
                                encodeOption(summary.characterId)
                            )
                        )
                });
            });
        }

        if (page > 1) {
            pageButtons.push(actionButton(
                'Previous',
                '!loot keys' + commandOption('page', page - 1)
            ));
        }

        if (page < pageCount) {
            pageButtons.push(actionButton(
                'Next',
                '!loot keys' + commandOption('page', page + 1)
            ));
        }

        if (pageButtons.length) {
            fields.push({
                label: 'Page ' + page + ' of ' + pageCount,
                value: pageButtons.join(' ')
            });
        }

        fields.push({
            label: 'Actions',
            value: actionButton('Prune Invalid Records', '!loot keys prune') + ' ' +
                actionButton(
                    'Clear All Keyrings',
                    '!loot keys clear-all' + commandOption(
                        'confirm',
                        keyConfirmationQuery('Clear all keyrings? Type yes to confirm')
                    )
                )
        });

        sendCard(msg, 'LootManager Keyrings', fields);
    }

    function showCharacterKeyring(msg, characterId, notice) {
        const cleanCharacterId = String(characterId || '');
        const character = cleanCharacterId ? getObj('character', cleanCharacterId) : null;
        const name = character
            ? String(character.get('name') || 'Unnamed Character')
            : 'Missing Character';
        const entries = getKeyringEntries(cleanCharacterId);
        const rawRecordCount = countKeyRecords(getKeyring(cleanCharacterId, false));
        const fields = [];

        if (notice) {
            fields.push({
                label: 'Result',
                value: escapeTemplate(notice)
            });
        }

        fields.push({
            label: 'Character',
            value: escapeTemplate(name)
        });
        fields.push({
            label: 'Character ID',
            value: escapeTemplate(cleanCharacterId)
        });

        if (!character) {
            fields.push({
                label: 'Status',
                value: 'This character no longer exists. Remove records or use Prune Invalid Records.'
            });
        }

        if (!entries.length) {
            fields.push({
                label: 'Keys',
                value: rawRecordCount
                    ? 'No valid keys are available. Use Prune Invalid Records.'
                    : 'No keys stored.'
            });
        } else {
            entries.forEach(function(entry) {
                fields.push({
                    label: entry.name,
                    value: actionButton(
                        'Remove',
                        '!loot keys remove' +
                        commandOption('character', encodeOption(cleanCharacterId)) +
                        commandOption('key', encodeOption(entry.normalizedName))
                    )
                });
            });
        }

        if (character) {
            fields.push({
                label: 'Grant Key',
                value: actionButton(
                    'Grant Key',
                    '!loot keys grant' +
                    commandOption('character', encodeOption(cleanCharacterId)) +
                    commandOption('key', '?&#123;Key Name&#125;')
                )
            });
        }

        fields.push({
            label: 'Actions',
            value: actionButton(
                'Clear Character Keyring',
                '!loot keys clear-character' +
                commandOption('character', encodeOption(cleanCharacterId)) +
                commandOption(
                    'confirm',
                    keyConfirmationQuery('Clear this character keyring? Type yes to confirm')
                )
            ) + ' ' + actionButton('Back', '!loot keys')
        });

        sendCard(msg, 'Character Keyring', fields);
    }

    function pruneKeyrings() {
        const keys = getKeyState();
        let missingCharacterRecords = 0;
        let emptyOrMalformedRecords = 0;
        let normalizedKeyRecords = 0;
        let retainedKeyrings = 0;
        let retainedKeyRecords = 0;

        Object.keys(keys).forEach(function(characterId) {
            const keyring = keys[characterId];

            if (!getObj('character', characterId)) {
                delete keys[characterId];
                missingCharacterRecords += 1;
                return;
            }

            if (!isKeyring(keyring)) {
                delete keys[characterId];
                emptyOrMalformedRecords += 1;
                return;
            }

            Object.keys(keyring).forEach(function(normalizedName) {
                const record = keyring[normalizedName];
                const name = record && typeof record.name === 'string'
                    ? cleanKeyName(record.name)
                    : '';
                const canonicalName = normalizeKeyName(name);
                const existingRecord = keyring[canonicalName];
                const existingName = existingRecord && typeof existingRecord.name === 'string'
                    ? cleanKeyName(existingRecord.name)
                    : '';

                if (
                    !name ||
                    !canonicalName
                ) {
                    delete keyring[normalizedName];
                    emptyOrMalformedRecords += 1;
                    return;
                }

                if (normalizedName !== canonicalName) {
                    if (
                        !existingName ||
                        normalizeKeyName(existingName) !== canonicalName
                    ) {
                        keyring[canonicalName] = {
                            name: name
                        };
                    }

                    delete keyring[normalizedName];
                    normalizedKeyRecords += 1;
                    return;
                }

                record.name = name;
            });

            if (!Object.keys(keyring).length) {
                delete keys[characterId];
                emptyOrMalformedRecords += 1;
                return;
            }

            retainedKeyrings += 1;
            retainedKeyRecords += Object.keys(keyring).length;
        });

        return {
            missingCharacterRecords: missingCharacterRecords,
            emptyOrMalformedRecords: emptyOrMalformedRecords,
            normalizedKeyRecords: normalizedKeyRecords,
            retainedKeyrings: retainedKeyrings,
            retainedKeyRecords: retainedKeyRecords
        };
    }

    function handleKeys(msg, command) {
        const action = String(command.positionals[0] || '').toLowerCase();
        const options = command.options || {};
        const characterId = decodeOption(options.character);
        const keyName = decodeOption(options.key);
        const confirmation = String(options.confirm || '').trim().toLowerCase();
        const character = characterId ? getObj('character', characterId) : null;
        let result;
        let removedCount;
        let summary;
        let keyringCount;
        let keyRecordCount;

        if (!playerIsGM(msg.playerid)) {
            sendError(msg, 'Only the GM can manage LootManager keyrings.');
            return;
        }

        switch (action) {
            case '':
                if (characterId) {
                    showCharacterKeyring(msg, characterId);
                } else {
                    showKeysMenu(msg, options.page);
                }
                break;

            case 'grant':
                if (!characterId || !character) {
                    sendError(msg, 'Specify an existing character before granting a key.');
                    return;
                }

                if (!cleanKeyName(keyName)) {
                    sendError(msg, 'Specify a nonblank key name.');
                    return;
                }

                result = grantCharacterKey(characterId, keyName);

                if (!result.ok) {
                    sendError(msg, 'The key name is invalid.');
                    return;
                }

                showCharacterKeyring(
                    msg,
                    characterId,
                    result.added
                        ? 'Granted ' + result.name + '.'
                        : result.name + ' was already present.'
                );
                break;

            case 'remove':
                if (!characterId || !cleanKeyName(keyName)) {
                    sendError(msg, 'Specify a character and key to remove.');
                    return;
                }

                if (!removeCharacterKey(characterId, keyName)) {
                    sendError(msg, 'That key is no longer in the character keyring.');
                    return;
                }

                if (getKeyring(characterId, false)) {
                    showCharacterKeyring(msg, characterId, 'Removed the selected key.');
                } else {
                    showKeysMenu(msg, options.page, 'Removed the selected keyring entry.');
                }
                break;

            case 'clear-character':
                if (!characterId) {
                    sendError(msg, 'Specify a character keyring to clear.');
                    return;
                }

                if (confirmation !== 'yes') {
                    sendError(msg, 'Clear Character Keyring requires --confirm|yes.');
                    return;
                }

                removedCount = countKeyRecords(getKeyring(characterId, false));
                delete getKeyState()[characterId];
                showKeysMenu(
                    msg,
                    options.page,
                    'Removed ' + removedCount + ' key record' +
                    (removedCount === 1 ? '' : 's') + '.'
                );
                break;

            case 'prune':
                summary = pruneKeyrings();
                showKeysMenu(
                    msg,
                    options.page,
                    'Pruned ' + summary.missingCharacterRecords +
                    ' missing-character record' +
                    (summary.missingCharacterRecords === 1 ? '' : 's') +
                    ' and ' + summary.emptyOrMalformedRecords +
                    ' empty or malformed record' +
                    (summary.emptyOrMalformedRecords === 1 ? '' : 's') +
                    ', normalized or coalesced ' + summary.normalizedKeyRecords +
                    ' key record' + (summary.normalizedKeyRecords === 1 ? '' : 's') +
                    '. Retained ' + summary.retainedKeyrings +
                    ' valid keyring' + (summary.retainedKeyrings === 1 ? '' : 's') +
                    ' with ' + summary.retainedKeyRecords + ' valid key record' +
                    (summary.retainedKeyRecords === 1 ? '' : 's') + '.'
                );
                break;

            case 'clear-all':
                if (confirmation !== 'yes') {
                    sendError(msg, 'Clear All Keyrings requires --confirm|yes.');
                    return;
                }

                keyringCount = Object.keys(getKeyState()).length;
                keyRecordCount = Object.keys(getKeyState()).reduce(function(total, currentCharacterId) {
                    return total + countKeyRecords(getKeyState()[currentCharacterId]);
                }, 0);
                state.LootManager.keys = {};
                showKeysMenu(
                    msg,
                    options.page,
                    'Removed ' + keyringCount + ' character keyring' +
                    (keyringCount === 1 ? '' : 's') + ' and ' + keyRecordCount +
                    ' key record' + (keyRecordCount === 1 ? '' : 's') + '.'
                );
                break;

            default:
                sendError(msg, 'Unknown keyring command. Use !loot keys to open the keyring menu.');
                break;
        }
    }

    function showHelp(msg) {
        sendCard(msg, 'LootManager Commands', [
            {
                label: 'Universal Loot Macro',
                value: '!loot &#64;&#123;selected&#124;token_id&#125; ' +
                    '&#64;&#123;target&#124;Loot&#124;token_id&#125;'
            },
            {
                label: 'Inspect Target Macro',
                value: '!loot inspect --token&#124;&#64;&#123;target&#124;Loot Source&#124;token_id&#125;'
            },
            {
                label: 'Existing Inspect Commands',
                value: '!loot inspect<br>!loot inspect TOKEN_ID<br>' +
                    '!loot inspect --token&#124;TOKEN_ID'
            },
            {
                label: 'Take Items',
                value: 'Use the buttons on the inspect card. Items are removed from the source but are not added to Beacon inventory.'
            },
            {
                label: 'Take Handouts',
                value: 'Handout entries grant the clicking player access and send that player the handout link. HandoutAccess must be loaded before a handout is taken.'
            },
            {
                label: 'Take Keys',
                value: 'key-item: Iron Gate Key adds a reusable key to the receiving linked character. Keys are stored by character ID and are not added to Beacon inventory.'
            },
            {
                label: 'Take Currency',
                value: 'Select the linked recipient token before using the gp button. Currency is added to that character\'s Beacon gp field.'
            },
            {
                label: 'Loot Block',
                value: 'LOOT<br>gp: 25<br>item: Potion of Healing<br>item: Crossbow Bolts &#124; 10<br>handout: Expedition Diary<br>key-item: Iron Gate Key<br>END LOOT'
            },
            {
                label: 'Locked Container Key',
                value: 'Use key: Iron Gate Key in a locked container LOOT block. A linked character with that reusable key receives a Use Key button; no Sleight of Hand roll is made.'
            },
            {
                label: 'GM Keyrings',
                value: '!loot keys opens character key management.'
            },
            {
                label: 'GM Configuration',
                value: '!loot config'
            }
        ]);
    }

    async function handleInput(msg) {
        const command = parseCommand(msg.content);
        const knownActions = {
            inspect: true,
            show: true,
            take: true,
            'unlock-check': true,
            'use-key': true,
            config: true,
            keys: true,
            help: true
        };
        let looterToken;
        let token;

        if (msg.type !== 'api' || !/^!loot(?:\s|$)/i.test(msg.content)) return;

        if (
            !knownActions[command.action] &&
            command.actionRaw &&
            command.positionals.length === 1
        ) {
            looterToken = resolveToken(msg, command.actionRaw);
            token = resolveToken(msg, command.positionals[0]);

            if (!looterToken || !token) {
                sendError(msg, 'The selected looter token or targeted loot token is invalid.');
                return;
            }

            await inspectLoot(msg, looterToken, token);
            return;
        }

        switch (command.action) {
            case 'inspect':
            case 'show':
                token = resolveToken(msg, command.options.token);

                if (!token) {
                    sendError(msg, 'Select a token or specify one with --token|TOKEN_ID.');
                    return;
                }

                await inspectLoot(msg, null, token);
                break;

            case 'take':
                await handleTake(msg, command.options);
                break;

            case 'unlock-check':
                if (command.positionals.length !== 2) {
                    sendError(
                        msg,
                        'Use !loot unlock-check LOOTER_TOKEN_ID CONTAINER_TOKEN_ID.'
                    );
                    return;
                }

                await handleUnlockCheck(
                    msg,
                    command.positionals[0],
                    command.positionals[1]
                );
                break;

            case 'use-key':
                if (command.positionals.length !== 2) {
                    sendError(
                        msg,
                        'Use !loot use-key LOOTER_TOKEN_ID CONTAINER_TOKEN_ID.'
                    );
                    return;
                }

                await handleUseKey(
                    msg,
                    command.positionals[0],
                    command.positionals[1],
                    command.options
                );
                break;

            case 'config':
                handleConfig(msg, command.options);
                break;

            case 'keys':
                handleKeys(msg, command);
                break;

            case 'help':
                showHelp(msg);
                break;

            default:
                sendError(msg, 'Unknown command. Use !loot help for the command list.');
                break;
        }
    }

    function registerEventHandlers() {
        on('chat:message', function(msg) {
            handleInput(msg).catch(function(error) {
                log(SCRIPT + ': Unexpected error: ' + error);
                sendError(msg, 'An unexpected error occurred. No further loot changes were attempted.');
            });
        });
    }

    on('ready', function() {
        checkInstall();
        registerEventHandlers();
    });

    return {
        inspect: function(tokenId) {
            const token = getObj('graphic', tokenId);
            return token && token.get('subtype') === 'token' ? getLoot(token) : null;
        }
    };
})();
